//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.17 at 11:24:08 PST 
//


package com.sbc.eia.bis.embus.service.netprovision.interfaces;


/**
 * Java content class for ErrorDetailType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/JAXB/netprovision/xml/NetProvision_20_0_0_002.xsd line 167)
 * <p>
 * <pre>
 * &lt;complexType name="ErrorDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgId" type="{http://www.syndesis.com/NN/XSNN}normal_string"/>
 *         &lt;element name="Message" type="{http://www.syndesis.com/NN/XSNN}long_string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ErrorDetailType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMessage();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMessage(java.lang.String value);

    boolean isSetMessage();

    void unsetMessage();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMsgId();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMsgId(java.lang.String value);

    boolean isSetMsgId();

    void unsetMsgId();

}
