//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.17 at 11:24:08 PST 
//


package com.sbc.eia.bis.embus.service.netprovision.interfaces;


/**
 * Java content class for ObjectItem complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/JAXB/netprovision/xml/NetProvision_20_0_0_002.xsd line 32)
 * <p>
 * <pre>
 * &lt;complexType name="ObjectItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.syndesis.com/NN/XSNN}normal_string"/>
 *         &lt;element name="Element" type="{http://www.syndesis.com/NN/XSNN}ElementItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Object" type="{http://www.syndesis.com/NN/XSNN}ObjectItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Index" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ObjectItem {


    /**
     * 
     */
    int getIndex();

    /**
     * 
     */
    void setIndex(int value);

    boolean isSetIndex();

    void unsetIndex();

    /**
     * Gets the value of the Element property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Element property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElement().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ElementItem}
     * 
     */
    java.util.List getElement();

    boolean isSetElement();

    void unsetElement();

    /**
     * Gets the value of the Object property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Object property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObject().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ObjectItem}
     * 
     */
    java.util.List getObject();

    boolean isSetObject();

    void unsetObject();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);

    boolean isSetName();

    void unsetName();

}
