//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.17 at 11:24:08 PST 
//


package com.sbc.eia.bis.embus.service.netprovision.interfaces;


/**
 * Java content class for ResponseItem complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/E:/JAXB/netprovision/xml/NetProvision_20_0_0_002.xsd line 113)
 * <p>
 * <pre>
 * &lt;complexType name="ResponseItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.syndesis.com/NN/XSNN}ObjectItem">
 *       &lt;sequence>
 *         &lt;element name="ServiceRequest" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiceOperation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Action" type="{http://www.syndesis.com/NN/XSNN}ActionEnum"/>
 *         &lt;element name="ResponseCode" type="{http://www.syndesis.com/NN/XSNN}ResponseCodeEnum"/>
 *         &lt;element name="FailureReason" type="{http://www.syndesis.com/NN/XSNN}ErrorMessage" minOccurs="0"/>
 *         &lt;element name="FailureDetails" type="{http://www.syndesis.com/NN/XSNN}ErrorDetailsMessage" minOccurs="0"/>
 *         &lt;element name="ResponseItem" type="{http://www.syndesis.com/NN/XSNN}ResponseItem" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ResponseItem
    extends com.sbc.eia.bis.embus.service.netprovision.interfaces.ObjectItem
{


    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorDetailsMessage}
     */
    com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorDetailsMessage getFailureDetails();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorDetailsMessage}
     */
    void setFailureDetails(com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorDetailsMessage value);

    boolean isSetFailureDetails();

    void unsetFailureDetails();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getAction();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setAction(java.lang.String value);

    boolean isSetAction();

    void unsetAction();

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ResponseItem}
     */
    com.sbc.eia.bis.embus.service.netprovision.interfaces.ResponseItem getResponseItem();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ResponseItem}
     */
    void setResponseItem(com.sbc.eia.bis.embus.service.netprovision.interfaces.ResponseItem value);

    boolean isSetResponseItem();

    void unsetResponseItem();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getServiceRequest();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setServiceRequest(java.lang.String value);

    boolean isSetServiceRequest();

    void unsetServiceRequest();

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorMessage}
     */
    com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorMessage getFailureReason();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorMessage}
     */
    void setFailureReason(com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorMessage value);

    boolean isSetFailureReason();

    void unsetFailureReason();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getServiceOperation();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setServiceOperation(java.lang.String value);

    boolean isSetServiceOperation();

    void unsetServiceOperation();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getResponseCode();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setResponseCode(java.lang.String value);

    boolean isSetResponseCode();

    void unsetResponseCode();

}
