//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces;


/**
 * Java content class for AVExceptionDetailsType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/bis_jaxb/npconnector_rmbisrequests/xml/NPConnector_2.1.0.xsd line 376)
 * <p>
 * <pre>
 * &lt;complexType name="AVExceptionDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="stack" type="{http://www.sbc.com/eia/rcl/netprovision}AVStackExceptionDetailsType"/>
 *         &lt;element name="save" type="{http://www.sbc.com/eia/rcl/netprovision}AVSaveExceptionDetailsType"/>
 *         &lt;element name="numbered" type="{http://www.sbc.com/eia/rcl/netprovision}AVNumberedExceptionDetailsType"/>
 *         &lt;element name="unNumbered" type="{http://www.sbc.com/eia/rcl/netprovision}AVUnNumberedExceptionDetailsType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AVExceptionDetailsType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType getStack();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType}
     */
    void setStack(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType getUnNumbered();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType}
     */
    void setUnNumbered(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType getNumbered();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType}
     */
    void setNumbered(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType getSave();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType}
     */
    void setSave(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType value);

}
