//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces;


/**
 * Java content class for AVSaveExceptionDetailsType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/bis_jaxb/npconnector_rmbisrequests/xml/NPConnector_2.1.0.xsd line 392)
 * <p>
 * <pre>
 * &lt;complexType name="AVSaveExceptionDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="errors" type="{http://www.sbc.com/eia/rcl/netprovision}ErrorMessageSeqType" minOccurs="0"/>
 *         &lt;element name="failedAttributes" type="{http://www.sbc.com/eia/rcl/netprovision}AttributeErrorItemSeqType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AVSaveExceptionDetailsType {


    /**
     * 
     */
    long getStatus();

    /**
     * 
     */
    void setStatus(long value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemSeqType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemSeqType getFailedAttributes();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemSeqType}
     */
    void setFailedAttributes(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemSeqType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageSeqType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageSeqType getErrors();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageSeqType}
     */
    void setErrors(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageSeqType value);

}
