//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces;


/**
 * Java content class for ExceptionType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/bis_jaxb/npconnector_rmbisrequests/xml/NPConnector_2.1.0.xsd line 298)
 * <p>
 * <pre>
 * &lt;complexType name="ExceptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="systemException" type="{http://www.sbc.com/eia/rcl/netprovision}SystemExceptionType"/>
 *         &lt;element name="nptException" type="{http://www.sbc.com/eia/rcl/netprovision}NptExceptionType"/>
 *         &lt;element name="nptGetValueException" type="{http://www.sbc.com/eia/rcl/netprovision}NptGetValueExceptionType"/>
 *         &lt;element name="nptSaveException" type="{http://www.sbc.com/eia/rcl/netprovision}NptSaveExceptionType"/>
 *         &lt;element name="avException" type="{http://www.sbc.com/eia/rcl/netprovision}AVExceptionType"/>
 *         &lt;element name="avAutoTransactionException" type="{http://www.sbc.com/eia/rcl/netprovision}AVAutoTransactionExceptionType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ExceptionType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType getSystemException();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType}
     */
    void setSystemException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType getNptException();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType}
     */
    void setNptException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType getAvAutoTransactionException();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType}
     */
    void setAvAutoTransactionException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType getNptSaveException();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType}
     */
    void setNptSaveException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType getNptGetValueException();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType}
     */
    void setNptGetValueException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType getAvException();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType}
     */
    void setAvException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType value);

}
