//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces;


/**
 * Java content class for ListerResponseType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/bis_jaxb/npconnector_rmbisrequests/xml/NPConnector_2.1.0.xsd line 178)
 * <p>
 * <pre>
 * &lt;complexType name="ListerResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="names" type="{http://www.sbc.com/eia/rcl/netprovision}AttributeItemSeqType" minOccurs="0"/>
 *         &lt;element name="results" type="{http://www.sbc.com/eia/rcl/netprovision}AttributeResultItemSeqSeqType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ListerResponseType {


    /**
     * 
     */
    long getCount();

    /**
     * 
     */
    void setCount(long value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqSeqType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqSeqType getResults();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqSeqType}
     */
    void setResults(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqSeqType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeItemSeqType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeItemSeqType getNames();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeItemSeqType}
     */
    void setNames(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeItemSeqType value);

}
