//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces;


/**
 * Java content class for NpResponseType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/bis_jaxb/npconnector_rmbisrequests/xml/NPConnector_2.1.0.xsd line 38)
 * <p>
 * <pre>
 * &lt;complexType name="NpResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="createServiceObjectResponse" type="{http://www.sbc.com/eia/rcl/netprovision}CreateServiceObjectResponseType"/>
 *         &lt;element name="modifyServiceObjectResponse" type="{http://www.sbc.com/eia/rcl/netprovision}ModifyServiceObjectResponseType"/>
 *         &lt;element name="deleteServiceObjectResponse" type="{http://www.sbc.com/eia/rcl/netprovision}DeleteServiceObjectResponseType"/>
 *         &lt;element name="getAllServiceObjectAttributesResponse" type="{http://www.sbc.com/eia/rcl/netprovision}GetAllServiceObjectAttributesResponseType"/>
 *         &lt;element name="createServiceElementResponse" type="{http://www.sbc.com/eia/rcl/netprovision}CreateServiceElementResponseType"/>
 *         &lt;element name="modifyServiceElementResponse" type="{http://www.sbc.com/eia/rcl/netprovision}ModifyServiceElementResponseType"/>
 *         &lt;element name="deleteServiceElementResponse" type="{http://www.sbc.com/eia/rcl/netprovision}DeleteServiceElementResponseType"/>
 *         &lt;element name="getServiceElementAttributesResponse" type="{http://www.sbc.com/eia/rcl/netprovision}GetServiceElementAttributesResponseType"/>
 *         &lt;element name="listerResponse" type="{http://www.sbc.com/eia/rcl/netprovision}ListerResponseType"/>
 *         &lt;element name="getAllErrorsResponse" type="{http://www.sbc.com/eia/rcl/netprovision}GetAllErrorsResponseType"/>
 *         &lt;element name="getSessionIdResponse" type="{http://www.sbc.com/eia/rcl/netprovision}GetSessionIdResponseType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface NpResponseType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType getGetSessionIdResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType}
     */
    void setGetSessionIdResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType getGetServiceElementAttributesResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType}
     */
    void setGetServiceElementAttributesResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType getModifyServiceElementResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType}
     */
    void setModifyServiceElementResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType getDeleteServiceElementResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType}
     */
    void setDeleteServiceElementResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType getModifyServiceObjectResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType}
     */
    void setModifyServiceObjectResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType getGetAllErrorsResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType}
     */
    void setGetAllErrorsResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType getListerResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType}
     */
    void setListerResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType getCreateServiceElementResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType}
     */
    void setCreateServiceElementResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType getCreateServiceObjectResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType}
     */
    void setCreateServiceObjectResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType getGetAllServiceObjectAttributesResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType}
     */
    void setGetAllServiceObjectAttributesResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType}
     */
    com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType getDeleteServiceObjectResponse();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType}
     */
    void setDeleteServiceObjectResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType value);

}
