//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap();
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.GrammarInfo grammarInfo = new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ObjectFactory.class));
    public final static java.lang.Class version = (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceObjectResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SearchItemType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SearchItemTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.UniqueByItemSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.UniqueByItemSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllServiceObjectAttributesRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SearchItemSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SearchItemSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceElementRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpRequestList.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpRequestListImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetServiceElementAttributesResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.OrderByItemSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.OrderByItemSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceObjectRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeErrorItemTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorStackType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ErrorStackTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVAutoTransactionExceptionTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ErrorMessageTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ListerRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.LogMessageSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.LogMessageSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVNumberedExceptionDetailsTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeValueItemSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeValueItemSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.LogMessageType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.LogMessageTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ErrorMessageSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpRequestSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpRequestSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceObjectResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptExceptionTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ListerResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeResultItemSeqSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceObjectResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceObjectRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVUnNumberedExceptionDetailsTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceElementResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVStackExceptionDetailsTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ExceptionType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ExceptionTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeValueItemType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeValueItemTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.OrderByItemType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.OrderByItemTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionDetailsType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionDetailsTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetServiceElementAttributesRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVSaveExceptionDetailsTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptGetValueExceptionTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseList.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseListImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeErrorItemSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SystemExceptionTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeResultItemSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeItemSeqType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeItemSeqTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectRequestType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceObjectRequestTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptSaveExceptionTypeImpl");
        defaultImplementations.put((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType.class), "com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllServiceObjectAttributesResponseTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://www.sbc.com/eia/rcl/netprovision", "npResponseList"), (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseList.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://www.sbc.com/eia/rcl/netprovision", "npRequestList"), (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpRequestList.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of ModifyServiceObjectResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType createModifyServiceObjectResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceObjectResponseTypeImpl();
    }

    /**
     * Create an instance of SearchItemType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SearchItemType createSearchItemType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SearchItemTypeImpl();
    }

    /**
     * Create an instance of UniqueByItemSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.UniqueByItemSeqType createUniqueByItemSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.UniqueByItemSeqTypeImpl();
    }

    /**
     * Create an instance of GetAllServiceObjectAttributesRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesRequestType createGetAllServiceObjectAttributesRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllServiceObjectAttributesRequestTypeImpl();
    }

    /**
     * Create an instance of SearchItemSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SearchItemSeqType createSearchItemSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SearchItemSeqTypeImpl();
    }

    /**
     * Create an instance of CreateServiceElementRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementRequestType createCreateServiceElementRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceElementRequestTypeImpl();
    }

    /**
     * Create an instance of NpRequestList
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpRequestList createNpRequestList()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpRequestListImpl();
    }

    /**
     * Create an instance of GetAllErrorsRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsRequestType createGetAllErrorsRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsRequestTypeImpl();
    }

    /**
     * Create an instance of GetServiceElementAttributesResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType createGetServiceElementAttributesResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetServiceElementAttributesResponseTypeImpl();
    }

    /**
     * Create an instance of ModifyServiceElementRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementRequestType createModifyServiceElementRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementRequestTypeImpl();
    }

    /**
     * Create an instance of GetSessionIdResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType createGetSessionIdResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl();
    }

    /**
     * Create an instance of OrderByItemSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.OrderByItemSeqType createOrderByItemSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.OrderByItemSeqTypeImpl();
    }

    /**
     * Create an instance of ModifyServiceElementResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType createModifyServiceElementResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl();
    }

    /**
     * Create an instance of ModifyServiceObjectRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectRequestType createModifyServiceObjectRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceObjectRequestTypeImpl();
    }

    /**
     * Create an instance of AttributeErrorItemType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemType createAttributeErrorItemType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeErrorItemTypeImpl();
    }

    /**
     * Create an instance of ErrorStackType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorStackType createErrorStackType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ErrorStackTypeImpl();
    }

    /**
     * Create an instance of GetAllErrorsResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType createGetAllErrorsResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl();
    }

    /**
     * Create an instance of AVAutoTransactionExceptionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType createAVAutoTransactionExceptionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVAutoTransactionExceptionTypeImpl();
    }

    /**
     * Create an instance of ErrorMessageType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageType createErrorMessageType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ErrorMessageTypeImpl();
    }

    /**
     * Create an instance of ListerRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerRequestType createListerRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ListerRequestTypeImpl();
    }

    /**
     * Create an instance of LogMessageSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.LogMessageSeqType createLogMessageSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.LogMessageSeqTypeImpl();
    }

    /**
     * Create an instance of AVNumberedExceptionDetailsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType createAVNumberedExceptionDetailsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVNumberedExceptionDetailsTypeImpl();
    }

    /**
     * Create an instance of NpResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseType createNpResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseTypeImpl();
    }

    /**
     * Create an instance of AttributeValueItemSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeValueItemSeqType createAttributeValueItemSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeValueItemSeqTypeImpl();
    }

    /**
     * Create an instance of LogMessageType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.LogMessageType createLogMessageType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.LogMessageTypeImpl();
    }

    /**
     * Create an instance of ErrorMessageSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ErrorMessageSeqType createErrorMessageSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ErrorMessageSeqTypeImpl();
    }

    /**
     * Create an instance of NpRequestSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpRequestSeqType createNpRequestSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpRequestSeqTypeImpl();
    }

    /**
     * Create an instance of GetSessionIdRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdRequestType createGetSessionIdRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdRequestTypeImpl();
    }

    /**
     * Create an instance of CreateServiceObjectResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType createCreateServiceObjectResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceObjectResponseTypeImpl();
    }

    /**
     * Create an instance of NptExceptionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType createNptExceptionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptExceptionTypeImpl();
    }

    /**
     * Create an instance of ListerResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType createListerResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ListerResponseTypeImpl();
    }

    /**
     * Create an instance of AVExceptionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType createAVExceptionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionTypeImpl();
    }

    /**
     * Create an instance of AttributeResultItemSeqSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqSeqType createAttributeResultItemSeqSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeResultItemSeqSeqTypeImpl();
    }

    /**
     * Create an instance of DeleteServiceObjectResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType createDeleteServiceObjectResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceObjectResponseTypeImpl();
    }

    /**
     * Create an instance of DeleteServiceObjectRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectRequestType createDeleteServiceObjectRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceObjectRequestTypeImpl();
    }

    /**
     * Create an instance of AVUnNumberedExceptionDetailsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType createAVUnNumberedExceptionDetailsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVUnNumberedExceptionDetailsTypeImpl();
    }

    /**
     * Create an instance of DeleteServiceElementRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementRequestType createDeleteServiceElementRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementRequestTypeImpl();
    }

    /**
     * Create an instance of CreateServiceElementResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType createCreateServiceElementResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceElementResponseTypeImpl();
    }

    /**
     * Create an instance of AVStackExceptionDetailsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType createAVStackExceptionDetailsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVStackExceptionDetailsTypeImpl();
    }

    /**
     * Create an instance of ExceptionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ExceptionType createExceptionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ExceptionTypeImpl();
    }

    /**
     * Create an instance of AttributeValueItemType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeValueItemType createAttributeValueItemType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeValueItemTypeImpl();
    }

    /**
     * Create an instance of OrderByItemType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.OrderByItemType createOrderByItemType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.OrderByItemTypeImpl();
    }

    /**
     * Create an instance of AVExceptionDetailsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionDetailsType createAVExceptionDetailsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionDetailsTypeImpl();
    }

    /**
     * Create an instance of GetServiceElementAttributesRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesRequestType createGetServiceElementAttributesRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetServiceElementAttributesRequestTypeImpl();
    }

    /**
     * Create an instance of NpResponseSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseSeqType createNpResponseSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseSeqTypeImpl();
    }

    /**
     * Create an instance of AVSaveExceptionDetailsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType createAVSaveExceptionDetailsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVSaveExceptionDetailsTypeImpl();
    }

    /**
     * Create an instance of NptGetValueExceptionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType createNptGetValueExceptionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptGetValueExceptionTypeImpl();
    }

    /**
     * Create an instance of DeleteServiceElementResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType createDeleteServiceElementResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl();
    }

    /**
     * Create an instance of NpResponseList
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseList createNpResponseList()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseListImpl();
    }

    /**
     * Create an instance of AttributeErrorItemSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeErrorItemSeqType createAttributeErrorItemSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeErrorItemSeqTypeImpl();
    }

    /**
     * Create an instance of SystemExceptionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType createSystemExceptionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SystemExceptionTypeImpl();
    }

    /**
     * Create an instance of AttributeResultItemSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeResultItemSeqType createAttributeResultItemSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeResultItemSeqTypeImpl();
    }

    /**
     * Create an instance of NpRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpRequestType createNpRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpRequestTypeImpl();
    }

    /**
     * Create an instance of AttributeItemSeqType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AttributeItemSeqType createAttributeItemSeqType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AttributeItemSeqTypeImpl();
    }

    /**
     * Create an instance of CreateServiceObjectRequestType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectRequestType createCreateServiceObjectRequestType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceObjectRequestTypeImpl();
    }

    /**
     * Create an instance of NptSaveExceptionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType createNptSaveExceptionType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptSaveExceptionTypeImpl();
    }

    /**
     * Create an instance of GetAllServiceObjectAttributesResponseType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType createGetAllServiceObjectAttributesResponseType()
        throws javax.xml.bind.JAXBException
    {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllServiceObjectAttributesResponseTypeImpl();
    }

}
