// $Id: FieldedAddressVector.java,v 1.1 2002/09/29 02:53:32 dm2328 Exp $

package com.sbc.eia.idl.lim.helpers;

/**
 * FieldedAddressVector defines constants associated with address.
 * Creation date: (5/3/01 12:09:01 PM)
 * @author: Rachel Zadok - Local
 */

public class FieldedAddressVector 
{
/**
 * FieldedAddressVector constructor.
 */

public FieldedAddressVector() {
	super();
}
/**
 * returns a vector with a list of allowed Level Names.
 * Creation date: (5/3/01 12:20:56 PM)
 * @return Vector
 */

 public final static java.util.Vector getLevelNameVector() 
{
	java.util.Vector UNIT_TYPE_NAME_VECTOR = new java.util.Vector();
	
	UNIT_TYPE_NAME_VECTOR.addElement("FLR");

	return UNIT_TYPE_NAME_VECTOR;
}
/**
 * returns a vector with a list of allowed Street Direction/Suffix Names.
 * Creation date: (5/3/01 12:00:00 PM)
 * @return Vector
 */

public final static java.util.Vector getStreetDirSufVector() {
	java.util.Vector STREET_DIRECTION_SUFFIX_VECTOR = new java.util.Vector();
	
	STREET_DIRECTION_SUFFIX_VECTOR.addElement("E");
	STREET_DIRECTION_SUFFIX_VECTOR.addElement("W");
	STREET_DIRECTION_SUFFIX_VECTOR.addElement("N");
	STREET_DIRECTION_SUFFIX_VECTOR.addElement("S");

	STREET_DIRECTION_SUFFIX_VECTOR.addElement("NE");
	STREET_DIRECTION_SUFFIX_VECTOR.addElement("NW");
	STREET_DIRECTION_SUFFIX_VECTOR.addElement("SE");
	STREET_DIRECTION_SUFFIX_VECTOR.addElement("SW");

	return STREET_DIRECTION_SUFFIX_VECTOR;
}
/**
 * returns a vector with a list of allowed Street Number Suffix Names.
 * Creation date: (5/3/01 12:20:56 PM)
 * @return Vector
 */

public final static java.util.Vector getStreetNumberSuffixVector() {
	java.util.Vector STREET_NUMBER_SUFFIX_VECTOR = new java.util.Vector();
	
	STREET_NUMBER_SUFFIX_VECTOR.addElement("1/2");
	STREET_NUMBER_SUFFIX_VECTOR.addElement("1/3");
	STREET_NUMBER_SUFFIX_VECTOR.addElement("1/4");

	return STREET_NUMBER_SUFFIX_VECTOR;
	// rz not sure if needed
}
/**
 * returns a vector with a list of allowed Strret Thoroughfare Names.
 * Creation date: (5/3/01 12:20:56 PM)
 * @return Vector
 */

public final static java.util.Vector getStreetThoroughfareVector() {
	java.util.Vector STREET_THOROUGHFARE_VECTOR = new java.util.Vector();

	STREET_THOROUGHFARE_VECTOR.addElement("ARFLD");
	STREET_THOROUGHFARE_VECTOR.addElement("ARPT");
	STREET_THOROUGHFARE_VECTOR.addElement("ALY");
	STREET_THOROUGHFARE_VECTOR.addElement("ANX");
	STREET_THOROUGHFARE_VECTOR.addElement("APT");
	STREET_THOROUGHFARE_VECTOR.addElement("ARCH");
	STREET_THOROUGHFARE_VECTOR.addElement("ARC");
	STREET_THOROUGHFARE_VECTOR.addElement("AV");
	STREET_THOROUGHFARE_VECTOR.addElement("AVE");

	STREET_THOROUGHFARE_VECTOR.addElement("BNK");
	STREET_THOROUGHFARE_VECTOR.addElement("BAY");
	STREET_THOROUGHFARE_VECTOR.addElement("BLDG");
	STREET_THOROUGHFARE_VECTOR.addElement("BRRKS");
	STREET_THOROUGHFARE_VECTOR.addElement("BS");
	STREET_THOROUGHFARE_VECTOR.addElement("BCH");
	STREET_THOROUGHFARE_VECTOR.addElement("BND");
	STREET_THOROUGHFARE_VECTOR.addElement("BLK");
	STREET_THOROUGHFARE_VECTOR.addElement("BLF");
	STREET_THOROUGHFARE_VECTOR.addElement("BDWK");
	STREET_THOROUGHFARE_VECTOR.addElement("BL");
	STREET_THOROUGHFARE_VECTOR.addElement("BLVD");
	STREET_THOROUGHFARE_VECTOR.addElement("BR");
	STREET_THOROUGHFARE_VECTOR.addElement("BRDG");
	STREET_THOROUGHFARE_VECTOR.addElement("BRK");
	
	STREET_THOROUGHFARE_VECTOR.addElement("CYN");
	STREET_THOROUGHFARE_VECTOR.addElement("CNYN");
	STREET_THOROUGHFARE_VECTOR.addElement("CAP");
	STREET_THOROUGHFARE_VECTOR.addElement("CSWY");
	STREET_THOROUGHFARE_VECTOR.addElement("CTR");
	STREET_THOROUGHFARE_VECTOR.addElement("CNTR");
	STREET_THOROUGHFARE_VECTOR.addElement("CIR");
	STREET_THOROUGHFARE_VECTOR.addElement("CR");
	STREET_THOROUGHFARE_VECTOR.addElement("CTY");
	STREET_THOROUGHFARE_VECTOR.addElement("CLS");
	STREET_THOROUGHFARE_VECTOR.addElement("CLG");
	STREET_THOROUGHFARE_VECTOR.addElement("CLNY");
	STREET_THOROUGHFARE_VECTOR.addElement("CMMN");
	STREET_THOROUGHFARE_VECTOR.addElement("CONC");
	STREET_THOROUGHFARE_VECTOR.addElement("COR");
	STREET_THOROUGHFARE_VECTOR.addElement("CORS");
	STREET_THOROUGHFARE_VECTOR.addElement("CTG");
	STREET_THOROUGHFARE_VECTOR.addElement("CT");
	STREET_THOROUGHFARE_VECTOR.addElement("CTHSE");
	STREET_THOROUGHFARE_VECTOR.addElement("CV");
	STREET_THOROUGHFARE_VECTOR.addElement("CREEK");
	STREET_THOROUGHFARE_VECTOR.addElement("CRK");
	STREET_THOROUGHFARE_VECTOR.addElement("CRES");
	STREET_THOROUGHFARE_VECTOR.addElement("CRST");
	STREET_THOROUGHFARE_VECTOR.addElement("CRS");
	STREET_THOROUGHFARE_VECTOR.addElement("CRSG");
	STREET_THOROUGHFARE_VECTOR.addElement("CRSRD");
	STREET_THOROUGHFARE_VECTOR.addElement("CRSWY");
	STREET_THOROUGHFARE_VECTOR.addElement("CURV");
	STREET_THOROUGHFARE_VECTOR.addElement("CO");
	// STREET_THOROUGHFARE_VECTOR.addElement("CALLE");
	// STREET_THOROUGHFARE_VECTOR.addElement("CLL");
	// STREET_THOROUGHFARE_VECTOR.addElement("CAMINITO");
	// STREET_THOROUGHFARE_VECTOR.addElement("CMT");
	// STREET_THOROUGHFARE_VECTOR.addElement("CAM");
	// STREET_THOROUGHFARE_VECTOR.addElement("CAMINO");
	// STREET_THOROUGHFARE_VECTOR.addElement("CER");
	// STREET_THOROUGHFARE_VECTOR.addElement("CERRADA");	
	// STREET_THOROUGHFARE_VECTOR.addElement("CIRCULO");	

	STREET_THOROUGHFARE_VECTOR.addElement("DL");
	STREET_THOROUGHFARE_VECTOR.addElement("DEP");
	STREET_THOROUGHFARE_VECTOR.addElement("DIST");
	STREET_THOROUGHFARE_VECTOR.addElement("DR");

	STREET_THOROUGHFARE_VECTOR.addElement("EAS");
	STREET_THOROUGHFARE_VECTOR.addElement("ESPLAND");
	STREET_THOROUGHFARE_VECTOR.addElement("ESPLND");
	STREET_THOROUGHFARE_VECTOR.addElement("EST");
	STREET_THOROUGHFARE_VECTOR.addElement("EXPWY");
	STREET_THOROUGHFARE_VECTOR.addElement("EXT");
	// STREET_THOROUGHFARE_VECTOR.addElement("ENT");
	// STREET_THOROUGHFARE_VECTOR.addElement("ENTRADA");

	STREET_THOROUGHFARE_VECTOR.addElement("FLS");
	STREET_THOROUGHFARE_VECTOR.addElement("FRM");
	STREET_THOROUGHFARE_VECTOR.addElement("FRMS");
	STREET_THOROUGHFARE_VECTOR.addElement("FRY");
	STREET_THOROUGHFARE_VECTOR.addElement("FLD");
	STREET_THOROUGHFARE_VECTOR.addElement("FLTS");
	STREET_THOROUGHFARE_VECTOR.addElement("FT");
	STREET_THOROUGHFARE_VECTOR.addElement("FRWY");
	STREET_THOROUGHFARE_VECTOR.addElement("FWY");

	STREET_THOROUGHFARE_VECTOR.addElement("GRDN");
	STREET_THOROUGHFARE_VECTOR.addElement("GRDNS");
	STREET_THOROUGHFARE_VECTOR.addElement("GATE");
	STREET_THOROUGHFARE_VECTOR.addElement("GLN");
	STREET_THOROUGHFARE_VECTOR.addElement("GRN");
	STREET_THOROUGHFARE_VECTOR.addElement("GRV");
	STREET_THOROUGHFARE_VECTOR.addElement("GRVS");

	STREET_THOROUGHFARE_VECTOR.addElement("HALL");
	STREET_THOROUGHFARE_VECTOR.addElement("HRBR");
	STREET_THOROUGHFARE_VECTOR.addElement("HD");
	STREET_THOROUGHFARE_VECTOR.addElement("HVN");
	STREET_THOROUGHFARE_VECTOR.addElement("HTS");
	STREET_THOROUGHFARE_VECTOR.addElement("HGTS");
	STREET_THOROUGHFARE_VECTOR.addElement("HWY");
	STREET_THOROUGHFARE_VECTOR.addElement("HL");
	STREET_THOROUGHFARE_VECTOR.addElement("HLS");
	STREET_THOROUGHFARE_VECTOR.addElement("HLSD");
	STREET_THOROUGHFARE_VECTOR.addElement("HLW");
	STREET_THOROUGHFARE_VECTOR.addElement("HSE");

	STREET_THOROUGHFARE_VECTOR.addElement("ISL");
	STREET_THOROUGHFARE_VECTOR.addElement("ISLE");
	
	STREET_THOROUGHFARE_VECTOR.addElement("JCTN");
	//STREET_THOROUGHFARE_VECTOR.addElement("JCT");

	STREET_THOROUGHFARE_VECTOR.addElement("KNL");
	STREET_THOROUGHFARE_VECTOR.addElement("KNLS");

	STREET_THOROUGHFARE_VECTOR.addElement("LK");
	STREET_THOROUGHFARE_VECTOR.addElement("LND");
	STREET_THOROUGHFARE_VECTOR.addElement("LNDG");
	STREET_THOROUGHFARE_VECTOR.addElement("LN");
	STREET_THOROUGHFARE_VECTOR.addElement("LA");
	STREET_THOROUGHFARE_VECTOR.addElement("LNK");
	STREET_THOROUGHFARE_VECTOR.addElement("LP");
	STREET_THOROUGHFARE_VECTOR.addElement("LOT");
	STREET_THOROUGHFARE_VECTOR.addElement("LOW");
	// STREET_THOROUGHFARE_VECTOR.addElement("LANE");

	STREET_THOROUGHFARE_VECTOR.addElement("ML");
	STREET_THOROUGHFARE_VECTOR.addElement("MNR");
	STREET_THOROUGHFARE_VECTOR.addElement("MKT");
	STREET_THOROUGHFARE_VECTOR.addElement("MRSH");
	STREET_THOROUGHFARE_VECTOR.addElement("MDW");
	STREET_THOROUGHFARE_VECTOR.addElement("MDWS");
	STREET_THOROUGHFARE_VECTOR.addElement("MEW");
	STREET_THOROUGHFARE_VECTOR.addElement("MLS");
	STREET_THOROUGHFARE_VECTOR.addElement("MT");
	STREET_THOROUGHFARE_VECTOR.addElement("MTN");

	STREET_THOROUGHFARE_VECTOR.addElement("NR");
	STREET_THOROUGHFARE_VECTOR.addElement("NK");
	STREET_THOROUGHFARE_VECTOR.addElement("NTCH");

	STREET_THOROUGHFARE_VECTOR.addElement("OKS");
	STREET_THOROUGHFARE_VECTOR.addElement("ORCHD");
	STREET_THOROUGHFARE_VECTOR.addElement("OV");
	
	STREET_THOROUGHFARE_VECTOR.addElement("PK");
	STREET_THOROUGHFARE_VECTOR.addElement("PKWY");
	STREET_THOROUGHFARE_VECTOR.addElement("PS");
	STREET_THOROUGHFARE_VECTOR.addElement("PA");
	STREET_THOROUGHFARE_VECTOR.addElement("PTH");
	STREET_THOROUGHFARE_VECTOR.addElement("PR");
	STREET_THOROUGHFARE_VECTOR.addElement("PKE");
	STREET_THOROUGHFARE_VECTOR.addElement("PL");
	STREET_THOROUGHFARE_VECTOR.addElement("PLN");
	STREET_THOROUGHFARE_VECTOR.addElement("PLNS");
	STREET_THOROUGHFARE_VECTOR.addElement("PLZ");
	STREET_THOROUGHFARE_VECTOR.addElement("PT");
	STREET_THOROUGHFARE_VECTOR.addElement("PD");
	STREET_THOROUGHFARE_VECTOR.addElement("PND");
	STREET_THOROUGHFARE_VECTOR.addElement("PROM");
	// STREET_THOROUGHFARE_VECTOR.addElement("PARK");
	// STREET_THOROUGHFARE_VECTOR.addElement("PKY");
	// STREET_THOROUGHFARE_VECTOR.addElement("PASEO");
	// STREET_THOROUGHFARE_VECTOR.addElement("PSO");
	// STREET_THOROUGHFARE_VECTOR.addElement("PLA");
	// STREET_THOROUGHFARE_VECTOR.addElement("PLACITA");

	STREET_THOROUGHFARE_VECTOR.addElement("QRTR");
	STREET_THOROUGHFARE_VECTOR.addElement("QRTRS");

	STREET_THOROUGHFARE_VECTOR.addElement("RR");
	STREET_THOROUGHFARE_VECTOR.addElement("RY");
	STREET_THOROUGHFARE_VECTOR.addElement("RL");
	STREET_THOROUGHFARE_VECTOR.addElement("RF");
	STREET_THOROUGHFARE_VECTOR.addElement("RSRVR");
	STREET_THOROUGHFARE_VECTOR.addElement("RDG");
	STREET_THOROUGHFARE_VECTOR.addElement("RVR");
	STREET_THOROUGHFARE_VECTOR.addElement("RD");
	STREET_THOROUGHFARE_VECTOR.addElement("RDWY");
	STREET_THOROUGHFARE_VECTOR.addElement("RCK");
	STREET_THOROUGHFARE_VECTOR.addElement("RT");
	STREET_THOROUGHFARE_VECTOR.addElement("RTE");
	STREET_THOROUGHFARE_VECTOR.addElement("ROW");
	STREET_THOROUGHFARE_VECTOR.addElement("RUE");
	STREET_THOROUGHFARE_VECTOR.addElement("RFD");
	// STREET_THOROUGHFARE_VECTOR.addElement("RANCHO");
	// STREET_THOROUGHFARE_VECTOR.addElement("RCH");
	// STREET_THOROUGHFARE_VECTOR.addElement("REAL");

	STREET_THOROUGHFARE_VECTOR.addElement("SH");
	STREET_THOROUGHFARE_VECTOR.addElement("SHR");
	STREET_THOROUGHFARE_VECTOR.addElement("SHRS");
	STREET_THOROUGHFARE_VECTOR.addElement("SHWY");
	STREET_THOROUGHFARE_VECTOR.addElement("SP");
	STREET_THOROUGHFARE_VECTOR.addElement("SQ");
	STREET_THOROUGHFARE_VECTOR.addElement("STA");
	STREET_THOROUGHFARE_VECTOR.addElement("ST");
	// STREET_THOROUGHFARE_VECTOR.addElement("SANTA");
	// STREET_THOROUGHFARE_VECTOR.addElement("SQ");	
		
	STREET_THOROUGHFARE_VECTOR.addElement("TERM");
	STREET_THOROUGHFARE_VECTOR.addElement("TERR");
	STREET_THOROUGHFARE_VECTOR.addElement("TER");
	STREET_THOROUGHFARE_VECTOR.addElement("TRK");
	STREET_THOROUGHFARE_VECTOR.addElement("TWR");
	STREET_THOROUGHFARE_VECTOR.addElement("THRWY");
	STREET_THOROUGHFARE_VECTOR.addElement("TWN");
	STREET_THOROUGHFARE_VECTOR.addElement("TRFWY");
	STREET_THOROUGHFARE_VECTOR.addElement("TR");
	STREET_THOROUGHFARE_VECTOR.addElement("TRL");
	STREET_THOROUGHFARE_VECTOR.addElement("TRLR");
	STREET_THOROUGHFARE_VECTOR.addElement("TUN");
	STREET_THOROUGHFARE_VECTOR.addElement("TRN");
	STREET_THOROUGHFARE_VECTOR.addElement("TRNPK");
	STREET_THOROUGHFARE_VECTOR.addElement("TNPK");

	STREET_THOROUGHFARE_VECTOR.addElement("UP");

	STREET_THOROUGHFARE_VECTOR.addElement("VAL");
	STREET_THOROUGHFARE_VECTOR.addElement("VLY");
	STREET_THOROUGHFARE_VECTOR.addElement("VDCT");
	STREET_THOROUGHFARE_VECTOR.addElement("VW");
	STREET_THOROUGHFARE_VECTOR.addElement("VLG");
	// STREET_THOROUGHFARE_VECTOR.addElement("VER");
	// STREET_THOROUGHFARE_VECTOR.addElement("VEREDA");
	// STREET_THOROUGHFARE_VECTOR.addElement("VIS");
	// STREET_THOROUGHFARE_VECTOR.addElement("VISTA");

	STREET_THOROUGHFARE_VECTOR.addElement("WK");
	STREET_THOROUGHFARE_VECTOR.addElement("WALK");
	STREET_THOROUGHFARE_VECTOR.addElement("WLK");
	STREET_THOROUGHFARE_VECTOR.addElement("WHSE");
	STREET_THOROUGHFARE_VECTOR.addElement("WAY");
	STREET_THOROUGHFARE_VECTOR.addElement("WY");
	STREET_THOROUGHFARE_VECTOR.addElement("WHF");
	STREET_THOROUGHFARE_VECTOR.addElement("WHRF");
	STREET_THOROUGHFARE_VECTOR.addElement("WD");

	STREET_THOROUGHFARE_VECTOR.addElement("YD");

	return STREET_THOROUGHFARE_VECTOR;
}
/**
 * returns a vector with a list of allowed Structure Names.
 * Creation date: (5/3/01 12:20:56 PM)
 * @return Vector
 */

public final static java.util.Vector getStructureNameVector() 
{
	java.util.Vector UNIT_TYPE_NAME_VECTOR = new java.util.Vector();
	
	UNIT_TYPE_NAME_VECTOR.addElement("BLDG");
	UNIT_TYPE_NAME_VECTOR.addElement("WING");
	UNIT_TYPE_NAME_VECTOR.addElement("WNG");
	UNIT_TYPE_NAME_VECTOR.addElement("PIER");
	UNIT_TYPE_NAME_VECTOR.addElement("TRLR");

	return UNIT_TYPE_NAME_VECTOR;
}
/**
 * returns a vector with a list of allowed Unit Names.
 * Creation date: (5/3/01 12:20:56 PM)
 * @return Vector
 */

public final static java.util.Vector getUnitNameVector() 
{
	java.util.Vector UNIT_TYPE_NAME_VECTOR = new java.util.Vector();
	
	UNIT_TYPE_NAME_VECTOR.addElement("APT");
	UNIT_TYPE_NAME_VECTOR.addElement("DRW");
	UNIT_TYPE_NAME_VECTOR.addElement("LOT");
	UNIT_TYPE_NAME_VECTOR.addElement("RM");
	UNIT_TYPE_NAME_VECTOR.addElement("SLIP");
	UNIT_TYPE_NAME_VECTOR.addElement("SUIT");
	UNIT_TYPE_NAME_VECTOR.addElement("UNIT");

	return UNIT_TYPE_NAME_VECTOR;
}
}
