//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl;

public class AVExceptionDetailsTypeImpl implements com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionDetailsType, com.sun.xml.bind.JAXBObject, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallableObject, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializable, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.ValidatableObject
{

    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType _Stack;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType _UnNumbered;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType _Numbered;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType _Save;
    public final static java.lang.Class version = (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionDetailsType.class);
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType getStack() {
        return _Stack;
    }

    public void setStack(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVStackExceptionDetailsType value) {
        _Stack = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType getUnNumbered() {
        return _UnNumbered;
    }

    public void setUnNumbered(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVUnNumberedExceptionDetailsType value) {
        _UnNumbered = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType getNumbered() {
        return _Numbered;
    }

    public void setNumbered(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVNumberedExceptionDetailsType value) {
        _Numbered = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType getSave() {
        return _Save;
    }

    public void setSave(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVSaveExceptionDetailsType value) {
        _Save = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context) {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionDetailsTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if ((((_Save == null)&&(_Numbered == null))&&(_Stack!= null))&&(_UnNumbered == null)) {
            context.startElement("", "stack");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Stack), "Stack");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Stack), "Stack");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Stack), "Stack");
            context.endElement();
        } else {
            if ((((_Save!= null)&&(_Numbered == null))&&(_Stack == null))&&(_UnNumbered == null)) {
                context.startElement("", "save");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Save), "Save");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Save), "Save");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Save), "Save");
                context.endElement();
            } else {
                if ((((_Save == null)&&(_Numbered!= null))&&(_Stack == null))&&(_UnNumbered == null)) {
                    context.startElement("", "numbered");
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Numbered), "Numbered");
                    context.endNamespaceDecls();
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Numbered), "Numbered");
                    context.endAttributes();
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _Numbered), "Numbered");
                    context.endElement();
                } else {
                    if ((((_Save == null)&&(_Numbered == null))&&(_Stack == null))&&(_UnNumbered!= null)) {
                        context.startElement("", "unNumbered");
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _UnNumbered), "UnNumbered");
                        context.endNamespaceDecls();
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _UnNumbered), "UnNumbered");
                        context.endAttributes();
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _UnNumbered), "UnNumbered");
                        context.endElement();
                    }
                }
            }
        }
    }

    public void serializeAttributes(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionDetailsType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/l"
+"ang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\f\u00b6\u0003\u0018ppsq\u0000~\u0000\u0000\n\u0006+\u00ffppsq\u0000~\u0000\u0000\u0006`\u00e7"
+"{ppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\t"
+"nameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.g"
+"rammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\f"
+"contentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0003\u00ec\u001bWpp\u0000sr\u0000\u001fcom.sun.msv.grammar.Sequen"
+"ceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0003\u00ec\u001bLppsq\u0000~\u0000\b\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsr\u0000 com"
+".sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.gram"
+"mar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000gT\u00e2sr\u0000\u0011java.lang.Bo"
+"olean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com.sun.msv.grammar.Attribut"
+"eExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\txq\u0000~\u0000\u0003\u0000gT\u00dfq\u0000~\u0000\u0014ps"
+"r\u00002com.sun.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u0013\u0001q\u0000~\u0000\u0018sr\u0000 com.sun.msv.grammar.AnyNameCla"
+"ss\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xps"
+"r\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u0019psr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq\u0000~\u0000"
+" xq\u0000~\u0000\u001bt\u0000fcom.sbc.eia.bis.embus.service.network.npconnector."
+"rmbisrequests.interfaces.AVStackExceptionDetailsTypet\u0000+http:"
+"//java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u0000\u0003\u0084\u00c6Oppsq\u0000~\u0000\u0015\u0003\u0084\u00c6D"
+"q\u0000~\u0000\u0014psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg"
+"/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/"
+"msv/util/StringPair;xq\u0000~\u0000\u0003\u0001\u0093\u00f6\u00f2ppsr\u0000\"com.sun.msv.datatype.xsd"
+".QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAto"
+"micType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000 L\u0000\btypeNameq\u0000~\u0000 L\u0000\nwhiteSpacet\u0000.Lcom"
+"/sun/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3"
+".org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.Whit"
+"eSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype."
+"xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar."
+"Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.s"
+"un.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespa"
+"ceURIq\u0000~\u0000 xpq\u0000~\u00001q\u0000~\u00000sq\u0000~\u0000\u001ft\u0000\u0004typet\u0000)http://www.w3.org/2001"
+"/XMLSchema-instanceq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0005stackt\u0000\u0000sq\u0000~\u0000\b\u0002t\u00cc\"pp\u0000sq\u0000~\u0000\f"
+"\u0002t\u00cc\u0017ppsq\u0000~\u0000\b\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0010\u0000gT\u00e2q\u0000~\u0000\u0014psq\u0000~\u0000\u0015\u0000gT\u00dfq\u0000~"
+"\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000ecom.sbc.eia.bis.embus.service.net"
+"work.npconnector.rmbisrequests.interfaces.AVSaveExceptionDet"
+"ailsTypeq\u0000~\u0000#sq\u0000~\u0000\u0000\u0002\rw\u001appsq\u0000~\u0000\u0015\u0002\rw\u000fq\u0000~\u0000\u0014pq\u0000~\u0000)sq\u0000~\u0000\u001fq\u0000~\u0000:q\u0000~"
+"\u0000;q\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0004saveq\u0000~\u0000>sq\u0000~\u0000\b\u0003\u00a5D\u0082pp\u0000sq\u0000~\u0000\f\u0003\u00a5Dwppsq\u0000~\u0000\b\u0000gT\u00f8"
+"pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0010\u0000gT\u00e2q\u0000~\u0000\u0014psq\u0000~\u0000\u0015\u0000gT\u00dfq\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~"
+"\u0000\u001esq\u0000~\u0000\u001ft\u0000icom.sbc.eia.bis.embus.service.network.npconnector"
+".rmbisrequests.interfaces.AVNumberedExceptionDetailsTypeq\u0000~\u0000"
+"#sq\u0000~\u0000\u0000\u0003=\u00efzppsq\u0000~\u0000\u0015\u0003=\u00efoq\u0000~\u0000\u0014pq\u0000~\u0000)sq\u0000~\u0000\u001fq\u0000~\u0000:q\u0000~\u0000;q\u0000~\u0000\u001esq\u0000~\u0000"
+"\u001ft\u0000\bnumberedq\u0000~\u0000>sq\u0000~\u0000\b\u0002\u00af\u00d7\u0017pp\u0000sq\u0000~\u0000\f\u0002\u00af\u00d7\fppsq\u0000~\u0000\b\u0000gT\u00f8pp\u0000sq\u0000~\u0000"
+"\u0000\u0000gT\u00edppsq\u0000~\u0000\u0010\u0000gT\u00e2q\u0000~\u0000\u0014psq\u0000~\u0000\u0015\u0000gT\u00dfq\u0000~\u0000\u0014pq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001f"
+"t\u0000kcom.sbc.eia.bis.embus.service.network.npconnector.rmbisre"
+"quests.interfaces.AVUnNumberedExceptionDetailsTypeq\u0000~\u0000#sq\u0000~\u0000"
+"\u0000\u0002H\u0082\u000fppsq\u0000~\u0000\u0015\u0002H\u0082\u0004q\u0000~\u0000\u0014pq\u0000~\u0000)sq\u0000~\u0000\u001fq\u0000~\u0000:q\u0000~\u0000;q\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\nun"
+"Numberedq\u0000~\u0000>sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHa"
+"sh;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8"
+"\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000g[\u0000\u0005tablet\u0000![Lcom/sun/"
+"msv/grammar/Expression;xp\u0000\u0000\u0000\u0013\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.grammar."
+"Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfppppppppppppppppppppppq\u0000~\u0000Mppppp"
+"ppppq\u0000~\u0000@q\u0000~\u0000\u0012q\u0000~\u0000$q\u0000~\u0000Cq\u0000~\u0000Pq\u0000~\u0000]ppppppq\u0000~\u0000\u000fq\u0000~\u0000Bq\u0000~\u0000Oq\u0000~\u0000\\"
+"pppppppppppppppppppppppppppppppppppppppppppppq\u0000~\u0000\rpppppppppp"
+"pppppppppppppppppppq\u0000~\u0000apppppppppppppppppppppppppq\u0000~\u0000\u0007pppq\u0000~"
+"\u0000Tpppppppppq\u0000~\u0000Gpppppppppppppppppppq\u0000~\u0000Zq\u0000~\u0000\u0006ppppq\u0000~\u0000\u0005p"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context) {
            super(context, "----------");
        }

        protected Unmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionDetailsTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        if (("status" == ___local)&&("" == ___uri)) {
                            _Save = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVSaveExceptionDetailsTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVSaveExceptionDetailsTypeImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  1 :
                        if (("exceptionClass" == ___local)&&("" == ___uri)) {
                            _UnNumbered = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVUnNumberedExceptionDetailsTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVUnNumberedExceptionDetailsTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  0 :
                        if (("stack" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        if (("save" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 6;
                            return ;
                        }
                        if (("numbered" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 8;
                            return ;
                        }
                        if (("unNumbered" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                    case  4 :
                        if (("status" == ___local)&&("" == ___uri)) {
                            _Stack = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVStackExceptionDetailsTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVStackExceptionDetailsTypeImpl.class), 5, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  8 :
                        if (("status" == ___local)&&("" == ___uri)) {
                            _Numbered = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVNumberedExceptionDetailsTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVNumberedExceptionDetailsTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  5 :
                        if (("stack" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  7 :
                        if (("save" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("unNumbered" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("numbered" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
