//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl;

public class ExceptionTypeImpl implements com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ExceptionType, com.sun.xml.bind.JAXBObject, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallableObject, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializable, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.ValidatableObject
{

    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType _SystemException;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType _NptException;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType _AvAutoTransactionException;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType _NptSaveException;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType _NptGetValueException;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType _AvException;
    public final static java.lang.Class version = (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ExceptionType.class);
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType getSystemException() {
        return _SystemException;
    }

    public void setSystemException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.SystemExceptionType value) {
        _SystemException = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType getNptException() {
        return _NptException;
    }

    public void setNptException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptExceptionType value) {
        _NptException = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType getAvAutoTransactionException() {
        return _AvAutoTransactionException;
    }

    public void setAvAutoTransactionException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVAutoTransactionExceptionType value) {
        _AvAutoTransactionException = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType getNptSaveException() {
        return _NptSaveException;
    }

    public void setNptSaveException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptSaveExceptionType value) {
        _NptSaveException = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType getNptGetValueException() {
        return _NptGetValueException;
    }

    public void setNptGetValueException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NptGetValueExceptionType value) {
        _NptGetValueException = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType getAvException() {
        return _AvException;
    }

    public void setAvException(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.AVExceptionType value) {
        _AvException = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context) {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ExceptionTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if ((((((_NptGetValueException == null)&&(_NptException == null))&&(_AvAutoTransactionException == null))&&(_NptSaveException == null))&&(_SystemException!= null))&&(_AvException == null)) {
            context.startElement("", "systemException");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _SystemException), "SystemException");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _SystemException), "SystemException");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _SystemException), "SystemException");
            context.endElement();
        } else {
            if ((((((_NptGetValueException == null)&&(_NptException!= null))&&(_AvAutoTransactionException == null))&&(_NptSaveException == null))&&(_SystemException == null))&&(_AvException == null)) {
                context.startElement("", "nptException");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _NptException), "NptException");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _NptException), "NptException");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _NptException), "NptException");
                context.endElement();
            } else {
                if ((((((_NptGetValueException!= null)&&(_NptException == null))&&(_AvAutoTransactionException == null))&&(_NptSaveException == null))&&(_SystemException == null))&&(_AvException == null)) {
                    context.startElement("", "nptGetValueException");
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _NptGetValueException), "NptGetValueException");
                    context.endNamespaceDecls();
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _NptGetValueException), "NptGetValueException");
                    context.endAttributes();
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _NptGetValueException), "NptGetValueException");
                    context.endElement();
                } else {
                    if ((((((_NptGetValueException == null)&&(_NptException == null))&&(_AvAutoTransactionException == null))&&(_NptSaveException!= null))&&(_SystemException == null))&&(_AvException == null)) {
                        context.startElement("", "nptSaveException");
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _NptSaveException), "NptSaveException");
                        context.endNamespaceDecls();
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _NptSaveException), "NptSaveException");
                        context.endAttributes();
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _NptSaveException), "NptSaveException");
                        context.endElement();
                    } else {
                        if ((((((_NptGetValueException == null)&&(_NptException == null))&&(_AvAutoTransactionException == null))&&(_NptSaveException == null))&&(_SystemException == null))&&(_AvException!= null)) {
                            context.startElement("", "avException");
                            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _AvException), "AvException");
                            context.endNamespaceDecls();
                            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _AvException), "AvException");
                            context.endAttributes();
                            context.childAsBody(((com.sun.xml.bind.JAXBObject) _AvException), "AvException");
                            context.endElement();
                        } else {
                            if ((((((_NptGetValueException == null)&&(_NptException == null))&&(_AvAutoTransactionException!= null))&&(_NptSaveException == null))&&(_SystemException == null))&&(_AvException == null)) {
                                context.startElement("", "avAutoTransactionException");
                                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _AvAutoTransactionException), "AvAutoTransactionException");
                                context.endNamespaceDecls();
                                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _AvAutoTransactionException), "AvAutoTransactionException");
                                context.endAttributes();
                                context.childAsBody(((com.sun.xml.bind.JAXBObject) _AvAutoTransactionException), "AvAutoTransactionException");
                                context.endElement();
                            }
                        }
                    }
                }
            }
        }
    }

    public void serializeAttributes(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ExceptionType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/l"
+"ang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u0010;\u00c88ppsq\u0000~\u0000\u0000\r\u00f3Q>ppsq\u0000~\u0000\u0000\n\u008a$"
+"\u00cfppsq\u0000~\u0000\u0000\bx\u00dd\u008fppsq\u0000~\u0000\u0000\u0005\u00bc&oppsr\u0000\'com.sun.msv.grammar.trex.Elem"
+"entPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/Nam"
+"eClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignor"
+"eUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0002`P\u00c2pp\u0000sr\u0000\u001fco"
+"m.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0002`P\u00b7ppsq\u0000~\u0000\n\u0000g"
+"T\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq"
+"\u0000~\u0000\u0003\u0000gT\u00e2sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com."
+"sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameCla"
+"ssq\u0000~\u0000\u000bxq\u0000~\u0000\u0003\u0000gT\u00dfq\u0000~\u0000\u0016psr\u00002com.sun.msv.grammar.Expression$An"
+"yStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u0015\u0001q\u0000~\u0000\u001asr\u0000 com.su"
+"n.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar"
+".NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$Ep"
+"silonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u001bpsr\u0000#com.sun.msv.gr"
+"ammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/St"
+"ring;L\u0000\fnamespaceURIq\u0000~\u0000\"xq\u0000~\u0000\u001dt\u0000^com.sbc.eia.bis.embus.serv"
+"ice.network.npconnector.rmbisrequests.interfaces.SystemExcep"
+"tionTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\u0000"
+"\u0001\u00f8\u00fb\u00bappsq\u0000~\u0000\u0017\u0001\u00f8\u00fb\u00afq\u0000~\u0000\u0016psr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004"
+"namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003\u0001\u0093\u00f6\u00f2ppsr\u0000\"com.sun."
+"msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatyp"
+"e.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.x"
+"sd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDat"
+"atypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\"L\u0000\btypeNameq\u0000~\u0000\"L\u0000\nw"
+"hiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xp"
+"t\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.d"
+"atatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.s"
+"un.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com."
+"sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNam"
+"eq\u0000~\u0000\"L\u0000\fnamespaceURIq\u0000~\u0000\"xpq\u0000~\u00003q\u0000~\u00002sq\u0000~\u0000!t\u0000\u0004typet\u0000)http:/"
+"/www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000 sq\u0000~\u0000!t\u0000\u000fsystemExcep"
+"tiont\u0000\u0000sq\u0000~\u0000\n\u0003[\u00d5\u00abpp\u0000sq\u0000~\u0000\u000e\u0003[\u00d5\u00a0ppsq\u0000~\u0000\n\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000"
+"~\u0000\u0012\u0000gT\u00e2q\u0000~\u0000\u0016psq\u0000~\u0000\u0017\u0000gT\u00dfq\u0000~\u0000\u0016pq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u0000[com.sbc"
+".eia.bis.embus.service.network.npconnector.rmbisrequests.int"
+"erfaces.NptExceptionTypeq\u0000~\u0000%sq\u0000~\u0000\u0000\u0002\u00f4\u0080\u00a3ppsq\u0000~\u0000\u0017\u0002\u00f4\u0080\u0098q\u0000~\u0000\u0016pq\u0000~"
+"\u0000+sq\u0000~\u0000!q\u0000~\u0000<q\u0000~\u0000=q\u0000~\u0000 sq\u0000~\u0000!t\u0000\fnptExceptionq\u0000~\u0000@sq\u0000~\u0000\n\u0002\u00bc\u00b7\u001ep"
+"p\u0000sq\u0000~\u0000\u000e\u0002\u00bc\u00b7\u0013ppsq\u0000~\u0000\n\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0012\u0000gT\u00e2q\u0000~\u0000\u0016psq\u0000~\u0000"
+"\u0017\u0000gT\u00dfq\u0000~\u0000\u0016pq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u0000ccom.sbc.eia.bis.embus.ser"
+"vice.network.npconnector.rmbisrequests.interfaces.NptGetValu"
+"eExceptionTypeq\u0000~\u0000%sq\u0000~\u0000\u0000\u0002Ub\u0016ppsq\u0000~\u0000\u0017\u0002Ub\u000bq\u0000~\u0000\u0016pq\u0000~\u0000+sq\u0000~\u0000!q\u0000"
+"~\u0000<q\u0000~\u0000=q\u0000~\u0000 sq\u0000~\u0000!t\u0000\u0014nptGetValueExceptionq\u0000~\u0000@sq\u0000~\u0000\n\u0002\u0011G>pp\u0000"
+"sq\u0000~\u0000\u000e\u0002\u0011G3ppsq\u0000~\u0000\n\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0012\u0000gT\u00e2q\u0000~\u0000\u0016psq\u0000~\u0000\u0017\u0000"
+"gT\u00dfq\u0000~\u0000\u0016pq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u0000_com.sbc.eia.bis.embus.servi"
+"ce.network.npconnector.rmbisrequests.interfaces.NptSaveExcep"
+"tionTypeq\u0000~\u0000%sq\u0000~\u0000\u0000\u0001\u00a9\u00f26ppsq\u0000~\u0000\u0017\u0001\u00a9\u00f2+q\u0000~\u0000\u0016pq\u0000~\u0000+sq\u0000~\u0000!q\u0000~\u0000<q\u0000~"
+"\u0000=q\u0000~\u0000 sq\u0000~\u0000!t\u0000\u0010nptSaveExceptionq\u0000~\u0000@sq\u0000~\u0000\n\u0003i,mpp\u0000sq\u0000~\u0000\u000e\u0003i,b"
+"ppsq\u0000~\u0000\n\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0012\u0000gT\u00e2q\u0000~\u0000\u0016psq\u0000~\u0000\u0017\u0000gT\u00dfq\u0000~\u0000\u0016pq"
+"\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!t\u0000Zcom.sbc.eia.bis.embus.service.network"
+".npconnector.rmbisrequests.interfaces.AVExceptionTypeq\u0000~\u0000%sq"
+"\u0000~\u0000\u0000\u0003\u0001\u00d7eppsq\u0000~\u0000\u0017\u0003\u0001\u00d7Zq\u0000~\u0000\u0016pq\u0000~\u0000+sq\u0000~\u0000!q\u0000~\u0000<q\u0000~\u0000=q\u0000~\u0000 sq\u0000~\u0000!t\u0000"
+"\u000bavExceptionq\u0000~\u0000@sq\u0000~\u0000\n\u0002Hv\u00f8pp\u0000sq\u0000~\u0000\u000e\u0002Hv\u00edppsq\u0000~\u0000\n\u0000gT\u00f8pp\u0000sq\u0000~\u0000"
+"\u0000\u0000gT\u00edppsq\u0000~\u0000\u0012\u0000gT\u00e2q\u0000~\u0000\u0016psq\u0000~\u0000\u0017\u0000gT\u00dfq\u0000~\u0000\u0016pq\u0000~\u0000\u001aq\u0000~\u0000\u001eq\u0000~\u0000 sq\u0000~\u0000!"
+"t\u0000icom.sbc.eia.bis.embus.service.network.npconnector.rmbisre"
+"quests.interfaces.AVAutoTransactionExceptionTypeq\u0000~\u0000%sq\u0000~\u0000\u0000\u0001"
+"\u00e1!\u00f0ppsq\u0000~\u0000\u0017\u0001\u00e1!\u00e5q\u0000~\u0000\u0016pq\u0000~\u0000+sq\u0000~\u0000!q\u0000~\u0000<q\u0000~\u0000=q\u0000~\u0000 sq\u0000~\u0000!t\u0000\u001aavAu"
+"toTransactionExceptionq\u0000~\u0000@sr\u0000\"com.sun.msv.grammar.Expressio"
+"nPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/Expressio"
+"nPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$Cl"
+"osedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000\u0083[\u0000\u0005tabl"
+"et\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u001d\u0000\u0000\u00009pur\u0000![Lcom.su"
+"n.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppppq\u0000~\u0000\bpppppppp"
+"ppq\u0000~\u0000&ppppppppq\u0000~\u0000\\pppppppq\u0000~\u0000\u0014q\u0000~\u0000Eq\u0000~\u0000Rq\u0000~\u0000_q\u0000~\u0000lq\u0000~\u0000yppp"
+"pq\u0000~\u0000\u0007q\u0000~\u0000\u0011q\u0000~\u0000Dq\u0000~\u0000Qq\u0000~\u0000^q\u0000~\u0000kq\u0000~\u0000xpppppq\u0000~\u0000\tpq\u0000~\u0000ppppppppp"
+"ppq\u0000~\u0000Vpppppppq\u0000~\u0000\u000fpq\u0000~\u0000}pppppppq\u0000~\u0000Ippppppppppppppppppppppp"
+"pppppppq\u0000~\u0000ippppppppppq\u0000~\u0000Oppppq\u0000~\u0000\u0005ppppq\u0000~\u0000vpppppppq\u0000~\u0000Bppp"
+"ppppppq\u0000~\u0000cppppppppppppppppq\u0000~\u0000\u0006ppppppppppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context) {
            super(context, "--------------");
        }

        protected Unmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ExceptionTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  0 :
                        if (("systemException" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 6;
                            return ;
                        }
                        if (("nptException" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 8;
                            return ;
                        }
                        if (("nptGetValueException" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        if (("nptSaveException" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        if (("avException" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 12;
                            return ;
                        }
                        if (("avAutoTransactionException" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        break;
                    case  10 :
                        if (("errorStack" == ___local)&&("" == ___uri)) {
                            _NptSaveException = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptSaveExceptionTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptSaveExceptionTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  12 :
                        if (("category" == ___local)&&("" == ___uri)) {
                            _AvException = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVExceptionTypeImpl.class), 13, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  8 :
                        if (("errorStack" == ___local)&&("" == ___uri)) {
                            _NptException = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptExceptionTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptExceptionTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  6 :
                        if (("exceptionClass" == ___local)&&("" == ___uri)) {
                            _SystemException = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SystemExceptionTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.SystemExceptionTypeImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  1 :
                        if (("errorStack" == ___local)&&("" == ___uri)) {
                            _NptGetValueException = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptGetValueExceptionTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NptGetValueExceptionTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  4 :
                        if (("category" == ___local)&&("" == ___uri)) {
                            _AvAutoTransactionException = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVAutoTransactionExceptionTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.AVAutoTransactionExceptionTypeImpl.class), 5, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  5 :
                        if (("avAutoTransactionException" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  7 :
                        if (("systemException" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("nptException" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("nptGetValueException" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("nptSaveException" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  13 :
                        if (("avException" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
