//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.09.09 at 11:03:57 PDT 
//


package com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl;

public class NpResponseTypeImpl implements com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseType, com.sun.xml.bind.JAXBObject, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallableObject, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializable, com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.ValidatableObject
{

    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType _GetSessionIdResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType _GetServiceElementAttributesResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType _ModifyServiceElementResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType _DeleteServiceElementResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType _ModifyServiceObjectResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType _GetAllErrorsResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType _ListerResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType _CreateServiceElementResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType _CreateServiceObjectResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType _GetAllServiceObjectAttributesResponse;
    protected com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType _DeleteServiceObjectResponse;
    public final static java.lang.Class version = (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseType.class);
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType getGetSessionIdResponse() {
        return _GetSessionIdResponse;
    }

    public void setGetSessionIdResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetSessionIdResponseType value) {
        _GetSessionIdResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType getGetServiceElementAttributesResponse() {
        return _GetServiceElementAttributesResponse;
    }

    public void setGetServiceElementAttributesResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetServiceElementAttributesResponseType value) {
        _GetServiceElementAttributesResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType getModifyServiceElementResponse() {
        return _ModifyServiceElementResponse;
    }

    public void setModifyServiceElementResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceElementResponseType value) {
        _ModifyServiceElementResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType getDeleteServiceElementResponse() {
        return _DeleteServiceElementResponse;
    }

    public void setDeleteServiceElementResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceElementResponseType value) {
        _DeleteServiceElementResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType getModifyServiceObjectResponse() {
        return _ModifyServiceObjectResponse;
    }

    public void setModifyServiceObjectResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ModifyServiceObjectResponseType value) {
        _ModifyServiceObjectResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType getGetAllErrorsResponse() {
        return _GetAllErrorsResponse;
    }

    public void setGetAllErrorsResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllErrorsResponseType value) {
        _GetAllErrorsResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType getListerResponse() {
        return _ListerResponse;
    }

    public void setListerResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.ListerResponseType value) {
        _ListerResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType getCreateServiceElementResponse() {
        return _CreateServiceElementResponse;
    }

    public void setCreateServiceElementResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceElementResponseType value) {
        _CreateServiceElementResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType getCreateServiceObjectResponse() {
        return _CreateServiceObjectResponse;
    }

    public void setCreateServiceObjectResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.CreateServiceObjectResponseType value) {
        _CreateServiceObjectResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType getGetAllServiceObjectAttributesResponse() {
        return _GetAllServiceObjectAttributesResponse;
    }

    public void setGetAllServiceObjectAttributesResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.GetAllServiceObjectAttributesResponseType value) {
        _GetAllServiceObjectAttributesResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType getDeleteServiceObjectResponse() {
        return _DeleteServiceObjectResponse;
    }

    public void setDeleteServiceObjectResponse(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.DeleteServiceObjectResponseType value) {
        _DeleteServiceObjectResponse = value;
    }

    public com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context) {
        return new com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse!= null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
            context.startElement("", "createServiceObjectResponse");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CreateServiceObjectResponse), "CreateServiceObjectResponse");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CreateServiceObjectResponse), "CreateServiceObjectResponse");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _CreateServiceObjectResponse), "CreateServiceObjectResponse");
            context.endElement();
        } else {
            if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse!= null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                context.startElement("", "modifyServiceObjectResponse");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ModifyServiceObjectResponse), "ModifyServiceObjectResponse");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ModifyServiceObjectResponse), "ModifyServiceObjectResponse");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _ModifyServiceObjectResponse), "ModifyServiceObjectResponse");
                context.endElement();
            } else {
                if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse!= null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                    context.startElement("", "deleteServiceObjectResponse");
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _DeleteServiceObjectResponse), "DeleteServiceObjectResponse");
                    context.endNamespaceDecls();
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _DeleteServiceObjectResponse), "DeleteServiceObjectResponse");
                    context.endAttributes();
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _DeleteServiceObjectResponse), "DeleteServiceObjectResponse");
                    context.endElement();
                } else {
                    if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse!= null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                        context.startElement("", "getAllServiceObjectAttributesResponse");
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _GetAllServiceObjectAttributesResponse), "GetAllServiceObjectAttributesResponse");
                        context.endNamespaceDecls();
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _GetAllServiceObjectAttributesResponse), "GetAllServiceObjectAttributesResponse");
                        context.endAttributes();
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _GetAllServiceObjectAttributesResponse), "GetAllServiceObjectAttributesResponse");
                        context.endElement();
                    } else {
                        if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse!= null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                            context.startElement("", "createServiceElementResponse");
                            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _CreateServiceElementResponse), "CreateServiceElementResponse");
                            context.endNamespaceDecls();
                            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _CreateServiceElementResponse), "CreateServiceElementResponse");
                            context.endAttributes();
                            context.childAsBody(((com.sun.xml.bind.JAXBObject) _CreateServiceElementResponse), "CreateServiceElementResponse");
                            context.endElement();
                        } else {
                            if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse!= null))&&(_GetAllErrorsResponse == null)) {
                                context.startElement("", "modifyServiceElementResponse");
                                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ModifyServiceElementResponse), "ModifyServiceElementResponse");
                                context.endNamespaceDecls();
                                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ModifyServiceElementResponse), "ModifyServiceElementResponse");
                                context.endAttributes();
                                context.childAsBody(((com.sun.xml.bind.JAXBObject) _ModifyServiceElementResponse), "ModifyServiceElementResponse");
                                context.endElement();
                            } else {
                                if (((((((((((_DeleteServiceElementResponse!= null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                                    context.startElement("", "deleteServiceElementResponse");
                                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _DeleteServiceElementResponse), "DeleteServiceElementResponse");
                                    context.endNamespaceDecls();
                                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _DeleteServiceElementResponse), "DeleteServiceElementResponse");
                                    context.endAttributes();
                                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _DeleteServiceElementResponse), "DeleteServiceElementResponse");
                                    context.endElement();
                                } else {
                                    if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse!= null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                                        context.startElement("", "getServiceElementAttributesResponse");
                                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _GetServiceElementAttributesResponse), "GetServiceElementAttributesResponse");
                                        context.endNamespaceDecls();
                                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _GetServiceElementAttributesResponse), "GetServiceElementAttributesResponse");
                                        context.endAttributes();
                                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _GetServiceElementAttributesResponse), "GetServiceElementAttributesResponse");
                                        context.endElement();
                                    } else {
                                        if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse!= null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                                            context.startElement("", "listerResponse");
                                            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _ListerResponse), "ListerResponse");
                                            context.endNamespaceDecls();
                                            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _ListerResponse), "ListerResponse");
                                            context.endAttributes();
                                            context.childAsBody(((com.sun.xml.bind.JAXBObject) _ListerResponse), "ListerResponse");
                                            context.endElement();
                                        } else {
                                            if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse == null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse!= null)) {
                                                context.startElement("", "getAllErrorsResponse");
                                                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _GetAllErrorsResponse), "GetAllErrorsResponse");
                                                context.endNamespaceDecls();
                                                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _GetAllErrorsResponse), "GetAllErrorsResponse");
                                                context.endAttributes();
                                                context.childAsBody(((com.sun.xml.bind.JAXBObject) _GetAllErrorsResponse), "GetAllErrorsResponse");
                                                context.endElement();
                                            } else {
                                                if (((((((((((_DeleteServiceElementResponse == null)&&(_GetServiceElementAttributesResponse == null))&&(_DeleteServiceObjectResponse == null))&&(_ModifyServiceObjectResponse == null))&&(_CreateServiceElementResponse == null))&&(_GetAllServiceObjectAttributesResponse == null))&&(_CreateServiceObjectResponse == null))&&(_GetSessionIdResponse!= null))&&(_ListerResponse == null))&&(_ModifyServiceElementResponse == null))&&(_GetAllErrorsResponse == null)) {
                                                    context.startElement("", "getSessionIdResponse");
                                                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _GetSessionIdResponse), "GetSessionIdResponse");
                                                    context.endNamespaceDecls();
                                                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _GetSessionIdResponse), "GetSessionIdResponse");
                                                    context.endAttributes();
                                                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _GetSessionIdResponse), "GetSessionIdResponse");
                                                    context.endElement();
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    public void serializeAttributes(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.NpResponseType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gramm"
+"ar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expression"
+"\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/l"
+"ang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u001e4\u008d\u00c3ppsq\u0000~\u0000\u0000\u001b\u009f\u00d4\u00f1ppsq\u0000~\u0000\u0000\u0018<\u0010"
+"\u00f1ppsq\u0000~\u0000\u0000\u0015\u00b2|\u00e4ppsq\u0000~\u0000\u0000\u0013f\u00e2\u001bppsq\u0000~\u0000\u0000\u000fy\u00ca\u001dppsq\u0000~\u0000\u0000\f\u0093\u0016-ppsq\u0000~\u0000\u0000\nQP"
+"\u0094ppsq\u0000~\u0000\u0000\bD\u001c[ppsq\u0000~\u0000\u0000\u0005\u00a8\u00e5\u00c9ppsr\u0000\'com.sun.msv.grammar.trex.Elem"
+"entPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/Nam"
+"eClass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignor"
+"eUndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0002g\u00a0\u0088pp\u0000sr\u0000\u001fco"
+"m.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0002g\u00a0}ppsq\u0000~\u0000\u000f\u0000g"
+"T\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq"
+"\u0000~\u0000\u0003\u0000gT\u00e2sr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000 com."
+"sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameCla"
+"ssq\u0000~\u0000\u0010xq\u0000~\u0000\u0003\u0000gT\u00dfq\u0000~\u0000\u001bpsr\u00002com.sun.msv.grammar.Expression$An"
+"yStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u001a\u0001q\u0000~\u0000\u001fsr\u0000 com.su"
+"n.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar"
+".NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$Ep"
+"silonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000 psr\u0000#com.sun.msv.gr"
+"ammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/St"
+"ring;L\u0000\fnamespaceURIq\u0000~\u0000\'xq\u0000~\u0000\"t\u0000jcom.sbc.eia.bis.embus.serv"
+"ice.network.npconnector.rmbisrequests.interfaces.CreateServi"
+"ceObjectResponseTypet\u0000+http://java.sun.com/jaxb/xjc/dummy-el"
+"ementssq\u0000~\u0000\u0000\u0002\u0000K\u0080ppsq\u0000~\u0000\u001c\u0002\u0000Kuq\u0000~\u0000\u001bpsr\u0000\u001bcom.sun.msv.grammar.Da"
+"taExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006ex"
+"ceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003\u0001\u0093\u00f6\u00f2pp"
+"sr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun"
+".msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.ms"
+"v.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.dataty"
+"pe.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\'L\u0000\btypeN"
+"ameq\u0000~\u0000\'L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpace"
+"Processor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0005QNamesr\u00005c"
+"om.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000"
+"\u0002L\u0000\tlocalNameq\u0000~\u0000\'L\u0000\fnamespaceURIq\u0000~\u0000\'xpq\u0000~\u00008q\u0000~\u00007sq\u0000~\u0000&t\u0000\u0004t"
+"ypet\u0000)http://www.w3.org/2001/XMLSchema-instanceq\u0000~\u0000%sq\u0000~\u0000&t\u0000"
+"\u001bcreateServiceObjectResponset\u0000\u0000sq\u0000~\u0000\u000f\u0003AE?pp\u0000sq\u0000~\u0000\u0013\u0003AE4ppsq\u0000~"
+"\u0000\u000f\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000"
+"~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000jcom.sbc.eia.bis.embus.service.network.npcon"
+"nector.rmbisrequests.interfaces.ModifyServiceObjectResponseT"
+"ypeq\u0000~\u0000*sq\u0000~\u0000\u0000\u0002\u00d9\u00f07ppsq\u0000~\u0000\u001c\u0002\u00d9\u00f0,q\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~"
+"\u0000%sq\u0000~\u0000&t\u0000\u001bmodifyServiceObjectResponseq\u0000~\u0000Esq\u0000~\u0000\u000f\u0002\u009b6\u0090pp\u0000sq\u0000~"
+"\u0000\u0013\u0002\u009b6\u0085ppsq\u0000~\u0000\u000f\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq"
+"\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000jcom.sbc.eia.bis.embus.service.n"
+"etwork.npconnector.rmbisrequests.interfaces.DeleteServiceObj"
+"ectResponseTypeq\u0000~\u0000*sq\u0000~\u0000\u0000\u00023\u00e1\u0088ppsq\u0000~\u0000\u001c\u00023\u00e1}q\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q"
+"\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000&t\u0000\u001bdeleteServiceObjectResponseq\u0000~\u0000Esq\u0000~\u0000"
+"\u000f\u0002\r47pp\u0000sq\u0000~\u0000\u0013\u0002\r4,ppsq\u0000~\u0000\u000f\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001b"
+"psq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000tcom.sbc.eia.bis.emb"
+"us.service.network.npconnector.rmbisrequests.interfaces.GetA"
+"llServiceObjectAttributesResponseTypeq\u0000~\u0000*sq\u0000~\u0000\u0000\u0001\u00a5\u00df/ppsq\u0000~\u0000\u001c"
+"\u0001\u00a5\u00df$q\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000&t\u0000%getAllServiceOb"
+"jectAttributesResponseq\u0000~\u0000Esq\u0000~\u0000\u000f\u0002A\u00c5\u0097pp\u0000sq\u0000~\u0000\u0013\u0002A\u00c5\u008cppsq\u0000~\u0000\u000f\u0000g"
+"T\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q"
+"\u0000~\u0000%sq\u0000~\u0000&t\u0000kcom.sbc.eia.bis.embus.service.network.npconnect"
+"or.rmbisrequests.interfaces.CreateServiceElementResponseType"
+"q\u0000~\u0000*sq\u0000~\u0000\u0000\u0001\u00dap\u008fppsq\u0000~\u0000\u001c\u0001\u00dap\u0084q\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%s"
+"q\u0000~\u0000&t\u0000\u001ccreateServiceElementResponseq\u0000~\u0000Esq\u0000~\u0000\u000f\u0002\u00e6\u00b3\u00eepp\u0000sq\u0000~\u0000\u0013"
+"\u0002\u00e6\u00b3\u00e3ppsq\u0000~\u0000\u000f\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~"
+"\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000kcom.sbc.eia.bis.embus.service.net"
+"work.npconnector.rmbisrequests.interfaces.ModifyServiceEleme"
+"ntResponseTypeq\u0000~\u0000*sq\u0000~\u0000\u0000\u0002\u007f^\u00e6ppsq\u0000~\u0000\u001c\u0002\u007f^\u00dbq\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000"
+"~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000&t\u0000\u001cmodifyServiceElementResponseq\u0000~\u0000Esq\u0000~\u0000"
+"\u000f\u0003\u00ed\u0017\u00fcpp\u0000sq\u0000~\u0000\u0013\u0003\u00ed\u0017\u00f1ppsq\u0000~\u0000\u000f\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001b"
+"psq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000kcom.sbc.eia.bis.emb"
+"us.service.network.npconnector.rmbisrequests.interfaces.Dele"
+"teServiceElementResponseTypeq\u0000~\u0000*sq\u0000~\u0000\u0000\u0003\u0085\u00c2\u00f4ppsq\u0000~\u0000\u001c\u0003\u0085\u00c2\u00e9q\u0000~\u0000\u001b"
+"pq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000&t\u0000\u001cdeleteServiceElementResp"
+"onseq\u0000~\u0000Esq\u0000~\u0000\u000f\u0002K\u009a\u00c7pp\u0000sq\u0000~\u0000\u0013\u0002K\u009a\u00bcppsq\u0000~\u0000\u000f\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edpps"
+"q\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000rcom.s"
+"bc.eia.bis.embus.service.network.npconnector.rmbisrequests.i"
+"nterfaces.GetServiceElementAttributesResponseTypeq\u0000~\u0000*sq\u0000~\u0000\u0000"
+"\u0001\u00e4E\u00bfppsq\u0000~\u0000\u001c\u0001\u00e4E\u00b4q\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000&t\u0000#get"
+"ServiceElementAttributesResponseq\u0000~\u0000Esq\u0000~\u0000\u000f\u0002\u0089\u0094\u000bpp\u0000sq\u0000~\u0000\u0013\u0002\u0089\u0094\u0000"
+"ppsq\u0000~\u0000\u000f\u0000gT\u00f8pp\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq"
+"\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq\u0000~\u0000&t\u0000]com.sbc.eia.bis.embus.service.network"
+".npconnector.rmbisrequests.interfaces.ListerResponseTypeq\u0000~\u0000"
+"*sq\u0000~\u0000\u0000\u0002\"?\u0003ppsq\u0000~\u0000\u001c\u0002\">\u00f8q\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000"
+"&t\u0000\u000elisterResponseq\u0000~\u0000Esq\u0000~\u0000\u000f\u0003c\u00c3\u00fepp\u0000sq\u0000~\u0000\u0013\u0003c\u00c3\u00f3ppsq\u0000~\u0000\u000f\u0000gT\u00f8pp"
+"\u0000sq\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%"
+"sq\u0000~\u0000&t\u0000ccom.sbc.eia.bis.embus.service.network.npconnector.r"
+"mbisrequests.interfaces.GetAllErrorsResponseTypeq\u0000~\u0000*sq\u0000~\u0000\u0000\u0002"
+"\u00fcn\u00f6ppsq\u0000~\u0000\u001c\u0002\u00fcn\u00ebq\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000&t\u0000\u0014getA"
+"llErrorsResponseq\u0000~\u0000Esq\u0000~\u0000\u000f\u0002\u0094\u00b8\u00d0pp\u0000sq\u0000~\u0000\u0013\u0002\u0094\u00b8\u00c5ppsq\u0000~\u0000\u000f\u0000gT\u00f8pp\u0000s"
+"q\u0000~\u0000\u0000\u0000gT\u00edppsq\u0000~\u0000\u0017\u0000gT\u00e2q\u0000~\u0000\u001bpsq\u0000~\u0000\u001c\u0000gT\u00dfq\u0000~\u0000\u001bpq\u0000~\u0000\u001fq\u0000~\u0000#q\u0000~\u0000%sq"
+"\u0000~\u0000&t\u0000ccom.sbc.eia.bis.embus.service.network.npconnector.rmb"
+"isrequests.interfaces.GetSessionIdResponseTypeq\u0000~\u0000*sq\u0000~\u0000\u0000\u0002-c"
+"\u00c8ppsq\u0000~\u0000\u001c\u0002-c\u00bdq\u0000~\u0000\u001bpq\u0000~\u00000sq\u0000~\u0000&q\u0000~\u0000Aq\u0000~\u0000Bq\u0000~\u0000%sq\u0000~\u0000&t\u0000\u0014getSes"
+"sionIdResponseq\u0000~\u0000Esr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$Cl"
+"osedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash"
+"\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000\u00c9[\u0000\u0005tablet\u0000![Lco"
+"m/sun/msv/grammar/Expression;xp\u0000\u0000\u00006\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.gr"
+"ammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppppq\u0000~\u0000\fpq\u0000~\u0000\u00afppq\u0000~\u0000\tpq\u0000"
+"~\u0000Gppq\u0000~\u0000[q\u0000~\u0000\u0095q\u0000~\u0000\u0005pppq\u0000~\u0000\u0088ppq\u0000~\u0000\u00bcppq\u0000~\u0000\u0082q\u0000~\u0000appq\u0000~\u0000\u0014pq\u0000~\u0000\u0019"
+"q\u0000~\u0000Jq\u0000~\u0000Wq\u0000~\u0000dq\u0000~\u0000qq\u0000~\u0000~q\u0000~\u0000\u008bq\u0000~\u0000\u0098q\u0000~\u0000\bq\u0000~\u0000\u00a5q\u0000~\u0000\u00a9q\u0000~\u0000\u0016q\u0000~\u0000I"
+"q\u0000~\u0000Vq\u0000~\u0000cq\u0000~\u0000pq\u0000~\u0000nq\u0000~\u0000}q\u0000~\u0000\u008aq\u0000~\u0000\u0097q\u0000~\u0000\u00a4q\u0000~\u0000\u00b2q\u0000~\u0000\u00b1q\u0000~\u0000\u00bfq\u0000~\u0000\u00be"
+"pppppppppq\u0000~\u0000\u000eq\u0000~\u0000\u000bppppppq\u0000~\u0000Tpppppppppppq\u0000~\u0000{pppppppppppq\u0000~"
+"\u0000\u00a2ppppppppppppppppppppppppppppppppppppppq\u0000~\u0000\u00b6ppppq\u0000~\u0000Nppq\u0000~\u0000"
+"\u009cpppq\u0000~\u0000\u0007pq\u0000~\u0000\u008fppq\u0000~\u0000\rq\u0000~\u0000\u00c3ppq\u0000~\u0000hppq\u0000~\u0000+ppppq\u0000~\u0000\nppq\u0000~\u0000\u0006ppp"
+"ppppppq\u0000~\u0000upppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context) {
            super(context, "------------------------");
        }

        protected Unmarshaller(com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.NpResponseTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  18 :
                        if (("id" == ___local)&&("" == ___uri)) {
                            _CreateServiceObjectResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceObjectResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceObjectResponseTypeImpl.class), 19, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  6 :
                        if (("attributeList" == ___local)&&("" == ___uri)) {
                            _DeleteServiceObjectResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceObjectResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceObjectResponseTypeImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  12 :
                        _DeleteServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl.class), 13, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  8 :
                        if (("attributeList" == ___local)&&("" == ___uri)) {
                            _GetServiceElementAttributesResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetServiceElementAttributesResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetServiceElementAttributesResponseTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  10 :
                        if (("count" == ___local)&&("" == ___uri)) {
                            _ListerResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ListerResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ListerResponseTypeImpl.class), 11, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  4 :
                        if (("id" == ___local)&&("" == ___uri)) {
                            _CreateServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceElementResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.CreateServiceElementResponseTypeImpl.class), 5, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  16 :
                        if (("sessionId" == ___local)&&("" == ___uri)) {
                            _GetSessionIdResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl.class), 17, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _GetSessionIdResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl.class), 17, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  1 :
                        if (("attributeList" == ___local)&&("" == ___uri)) {
                            _ModifyServiceObjectResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceObjectResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceObjectResponseTypeImpl.class), 2, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  22 :
                        _ModifyServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl.class), 23, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  14 :
                        if (("attributeList" == ___local)&&("" == ___uri)) {
                            _GetAllServiceObjectAttributesResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllServiceObjectAttributesResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllServiceObjectAttributesResponseTypeImpl.class), 15, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  0 :
                        if (("createServiceObjectResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 18;
                            return ;
                        }
                        if (("modifyServiceObjectResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        if (("deleteServiceObjectResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 6;
                            return ;
                        }
                        if (("getAllServiceObjectAttributesResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 14;
                            return ;
                        }
                        if (("createServiceElementResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 4;
                            return ;
                        }
                        if (("modifyServiceElementResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 22;
                            return ;
                        }
                        if (("deleteServiceElementResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 12;
                            return ;
                        }
                        if (("getServiceElementAttributesResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 8;
                            return ;
                        }
                        if (("listerResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 10;
                            return ;
                        }
                        if (("getAllErrorsResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 20;
                            return ;
                        }
                        if (("getSessionIdResponse" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 16;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("logMessageList" == ___local)&&("" == ___uri)) {
                            _GetAllErrorsResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl.class), 21, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _GetAllErrorsResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl.class), 21, ___uri, ___local, ___qname, __atts));
                        return ;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  13 :
                        if (("deleteServiceElementResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  23 :
                        if (("modifyServiceElementResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  12 :
                        _DeleteServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl) spawnChildFromLeaveElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl.class), 13, ___uri, ___local, ___qname));
                        return ;
                    case  15 :
                        if (("getAllServiceObjectAttributesResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  19 :
                        if (("createServiceObjectResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  21 :
                        if (("getAllErrorsResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("modifyServiceObjectResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("listerResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  7 :
                        if (("deleteServiceObjectResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("getServiceElementAttributesResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  16 :
                        _GetSessionIdResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl) spawnChildFromLeaveElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  22 :
                        _ModifyServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl) spawnChildFromLeaveElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl.class), 23, ___uri, ___local, ___qname));
                        return ;
                    case  5 :
                        if (("createServiceElementResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("getSessionIdResponse" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  20 :
                        _GetAllErrorsResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl) spawnChildFromLeaveElement((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl.class), 21, ___uri, ___local, ___qname));
                        return ;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        _DeleteServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl) spawnChildFromEnterAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl.class), 13, ___uri, ___local, ___qname));
                        return ;
                    case  16 :
                        _GetSessionIdResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl) spawnChildFromEnterAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  22 :
                        _ModifyServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl) spawnChildFromEnterAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl.class), 23, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  20 :
                        _GetAllErrorsResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl) spawnChildFromEnterAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl.class), 21, ___uri, ___local, ___qname));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  12 :
                        _DeleteServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl) spawnChildFromLeaveAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl.class), 13, ___uri, ___local, ___qname));
                        return ;
                    case  16 :
                        _GetSessionIdResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl) spawnChildFromLeaveAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  22 :
                        _ModifyServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl) spawnChildFromLeaveAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl.class), 23, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  20 :
                        _GetAllErrorsResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl) spawnChildFromLeaveAttribute((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl.class), 21, ___uri, ___local, ___qname));
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  12 :
                            _DeleteServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl) spawnChildFromText((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.DeleteServiceElementResponseTypeImpl.class), 13, value));
                            return ;
                        case  16 :
                            _GetSessionIdResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl) spawnChildFromText((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetSessionIdResponseTypeImpl.class), 17, value));
                            return ;
                        case  22 :
                            _ModifyServiceElementResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl) spawnChildFromText((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.ModifyServiceElementResponseTypeImpl.class), 23, value));
                            return ;
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  20 :
                            _GetAllErrorsResponse = ((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl) spawnChildFromText((com.sbc.eia.bis.embus.service.network.npconnector.rmbisrequests.interfaces.impl.GetAllErrorsResponseTypeImpl.class), 21, value));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
