//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.11.17 at 11:24:08 PST 
//


package com.sbc.eia.bis.embus.service.netprovision.interfaces.impl;

public class ExceptionResponseTypeImpl implements com.sbc.eia.bis.embus.service.netprovision.interfaces.ExceptionResponseType, java.io.Serializable, com.sun.xml.bind.JAXBObject, com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.UnmarshallableObject, com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.XMLSerializable, com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.ValidatableObject
{

    private final static long serialVersionUID = 5000L;
    protected com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorDetailsMessage _FailureDetails;
    protected java.lang.String _DesignId;
    protected java.lang.String _SchemaVersion;
    protected java.lang.String _ActivityId;
    protected com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorMessage _FailureReason;
    protected java.lang.String _OrderId;
    public final static java.lang.Class version = (com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (com.sbc.eia.bis.embus.service.netprovision.interfaces.ExceptionResponseType.class);
    }

    public com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorDetailsMessage getFailureDetails() {
        return _FailureDetails;
    }

    public void setFailureDetails(com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorDetailsMessage value) {
        _FailureDetails = value;
    }

    public boolean isSetFailureDetails() {
        return (_FailureDetails!= null);
    }

    public void unsetFailureDetails() {
        _FailureDetails = null;
    }

    public java.lang.String getDesignId() {
        return _DesignId;
    }

    public void setDesignId(java.lang.String value) {
        _DesignId = value;
    }

    public boolean isSetDesignId() {
        return (_DesignId!= null);
    }

    public void unsetDesignId() {
        _DesignId = null;
    }

    public java.lang.String getSchemaVersion() {
        if (_SchemaVersion == null) {
            return "20.0.0.002";
        } else {
            return _SchemaVersion;
        }
    }

    public void setSchemaVersion(java.lang.String value) {
        _SchemaVersion = value;
    }

    public boolean isSetSchemaVersion() {
        return (_SchemaVersion!= null);
    }

    public void unsetSchemaVersion() {
        _SchemaVersion = null;
    }

    public java.lang.String getActivityId() {
        return _ActivityId;
    }

    public void setActivityId(java.lang.String value) {
        _ActivityId = value;
    }

    public boolean isSetActivityId() {
        return (_ActivityId!= null);
    }

    public void unsetActivityId() {
        _ActivityId = null;
    }

    public com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorMessage getFailureReason() {
        return _FailureReason;
    }

    public void setFailureReason(com.sbc.eia.bis.embus.service.netprovision.interfaces.ErrorMessage value) {
        _FailureReason = value;
    }

    public boolean isSetFailureReason() {
        return (_FailureReason!= null);
    }

    public void unsetFailureReason() {
        _FailureReason = null;
    }

    public java.lang.String getOrderId() {
        return _OrderId;
    }

    public void setOrderId(java.lang.String value) {
        _OrderId = value;
    }

    public boolean isSetOrderId() {
        return (_OrderId!= null);
    }

    public void unsetOrderId() {
        _OrderId = null;
    }

    public com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.UnmarshallingEventHandler createUnmarshaller(com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.UnmarshallingContext context) {
        return new com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ExceptionResponseTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_OrderId!= null) {
            context.startElement("", "OrderId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _OrderId), "OrderId");
            } catch (java.lang.Exception e) {
                com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_ActivityId!= null) {
            context.startElement("", "ActivityId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ActivityId), "ActivityId");
            } catch (java.lang.Exception e) {
                com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_DesignId!= null) {
            context.startElement("", "DesignId");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _DesignId), "DesignId");
            } catch (java.lang.Exception e) {
                com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        context.startElement("", "FailureReason");
        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _FailureReason), "FailureReason");
        context.endNamespaceDecls();
        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _FailureReason), "FailureReason");
        context.endAttributes();
        context.childAsBody(((com.sun.xml.bind.JAXBObject) _FailureReason), "FailureReason");
        context.endElement();
        if (_FailureDetails!= null) {
            context.startElement("", "FailureDetails");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _FailureDetails), "FailureDetails");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _FailureDetails), "FailureDetails");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _FailureDetails), "FailureDetails");
            context.endElement();
        }
    }

    public void serializeAttributes(com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_SchemaVersion!= null) {
            context.startAttribute("", "SchemaVersion");
            try {
                context.text(((java.lang.String) _SchemaVersion), "SchemaVersion");
            } catch (java.lang.Exception e) {
                com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
    }

    public void serializeURIs(com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (com.sbc.eia.bis.embus.service.netprovision.interfaces.ExceptionResponseType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava"
+"/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\n\u00fd\u00e3[ppsq\u0000~\u0000\u0000\t\u00c5\u0003wppsq\u0000~\u0000\u0000\b"
+"\u0006P\u00a5ppsq\u0000~\u0000\u0000\u0006\u00e5d\u00c0ppsq\u0000~\u0000\u0000\u00042\u008eLppsr\u0000\u001dcom.sun.msv.grammar.ChoiceE"
+"xp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0002\t\u00c1\u00abppsr\u0000\'com.sun.msv.grammar.trex.Elemen"
+"tPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameC"
+"lass;xr\u0000\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreU"
+"ndeclaredAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0002\t\u00c1\u00a0sr\u0000\u0011java.la"
+"ng.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000p\u0000sq\u0000~\u0000\u0000\u0002\t\u00c1\u0095ppsr\u0000\u001bcom.sun.ms"
+"v.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Da"
+"tatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;"
+"xq\u0000~\u0000\u0003\u0000\u0019\u0089\u00c5ppsr\u0000\'com.sun.msv.datatype.xsd.MaxLengthFacet\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tmaxLengthxr\u00009com.sun.msv.datatype.xsd.DataTypeWithV"
+"alueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.D"
+"ataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckF"
+"lagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;L\u0000"
+"\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfa"
+"cetNamet\u0000\u0012Ljava/lang/String;xr\u0000\'com.sun.msv.datatype.xsd.XSD"
+"atatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000\u001cL\u0000\btypeNameq\u0000~\u0000\u001cL\u0000"
+"\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;"
+"xpt\u0000\u001fhttp://www.syndesis.com/NN/XSNNt\u0000\u000blong_stringsr\u00005com.su"
+"n.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr"
+"\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0000"
+"\u0000sr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwa"
+"ysValidxr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000\u001dt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringq\u0000~\u0000$\u0001q\u0000~\u0000(t\u0000\t"
+"maxLength\u0000\u0000\u0000\u00ffsr\u00000com.sun.msv.grammar.Expression$NullSetExpre"
+"ssion\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0"
+"t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq\u0000~\u0000\u001cxpq\u0000~\u0000!q\u0000~\u0000 s"
+"q\u0000~\u0000\n\u0001\u00f07\u00cbppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000"
+"\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\rxq\u0000~\u0000\u0003\u0001\u00f07\u00c0q\u0000~\u0000\u0011psq\u0000~\u0000\u0013\u0000A\u009d\u0015ppsr\u0000\"co"
+"m.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000&q\u0000~\u0000)t\u0000\u0005QNa"
+"mesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor$Collapse\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000#q\u0000~\u0000-sq\u0000~\u0000.q\u0000~\u00006q\u0000~\u0000)sr\u0000#com.sun.msv.grammar"
+".SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u001cL\u0000\fnamespaceURIq"
+"\u0000~\u0000\u001cxr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)"
+"http://www.w3.org/2001/XMLSchema-instancesr\u00000com.sun.msv.gra"
+"mmar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tsq\u0000~\u0000\u0010"
+"\u0001psq\u0000~\u0000:t\u0000\u0007OrderIdt\u0000\u0000q\u0000~\u0000@sq\u0000~\u0000\n\u0002(\u00cc\u009cppsq\u0000~\u0000\f\u0002(\u00cc\u0091q\u0000~\u0000\u0011p\u0000sq\u0000~\u0000"
+"\u0000\u0002(\u00cc\u0086ppq\u0000~\u0000\u0016sq\u0000~\u0000\n\u0002\u000fB\u00bcppsq\u0000~\u00001\u0002\u000fB\u00b1q\u0000~\u0000\u0011pq\u0000~\u00003sq\u0000~\u0000:q\u0000~\u0000=q\u0000~\u0000"
+">q\u0000~\u0000@sq\u0000~\u0000:t\u0000\nActivityIdq\u0000~\u0000Dq\u0000~\u0000@sq\u0000~\u0000\n\u0002\u00b2\u00d6oppsq\u0000~\u0000\f\u0002\u00b2\u00d6dq\u0000~"
+"\u0000\u0011p\u0000sq\u0000~\u0000\u0000\u0002\u00b2\u00d6Yppsq\u0000~\u0000\u0013\u0000x|&ppsq\u0000~\u0000\u0017q\u0000~\u0000 t\u0000\rnormal_stringq\u0000~\u0000$"
+"\u0000\u0000q\u0000~\u0000(q\u0000~\u0000(q\u0000~\u0000+\u0000\u0000\u0000@q\u0000~\u0000-sq\u0000~\u0000.q\u0000~\u0000Rq\u0000~\u0000 sq\u0000~\u0000\n\u0002:Z.ppsq\u0000~\u00001"
+"\u0002:Z#q\u0000~\u0000\u0011pq\u0000~\u00003sq\u0000~\u0000:q\u0000~\u0000=q\u0000~\u0000>q\u0000~\u0000@sq\u0000~\u0000:t\u0000\bDesignIdq\u0000~\u0000Dq\u0000"
+"~\u0000@sq\u0000~\u0000\f\u0001 \u00eb\u00e0pp\u0000sq\u0000~\u0000\u0000\u0001 \u00eb\u00d5ppsq\u0000~\u0000\f\u0000\u001e\u00ecWpp\u0000sq\u0000~\u0000\n\u0000\u001e\u00ecLppsr\u0000 com"
+".sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.gram"
+"mar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000\u001e\u00ecAq\u0000~\u0000\u0011psq\u0000~\u00001\u0000\u001e\u00ec>"
+"q\u0000~\u0000\u0011psr\u00002com.sun.msv.grammar.Expression$AnyStringExpression"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bq\u0000~\u0000Aq\u0000~\u0000bsr\u0000 com.sun.msv.grammar.AnyNa"
+"meClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000;q\u0000~\u0000@sq\u0000~\u0000:t\u0000Bcom.sbc.eia.bis.embus."
+"service.netprovision.interfaces.ErrorMessaget\u0000+http://java.s"
+"un.com/jaxb/xjc/dummy-elementssq\u0000~\u0000\n\u0001\u0001\u00ffyppsq\u0000~\u00001\u0001\u0001\u00ffnq\u0000~\u0000\u0011pq\u0000"
+"~\u00003sq\u0000~\u0000:q\u0000~\u0000=q\u0000~\u0000>q\u0000~\u0000@sq\u0000~\u0000:t\u0000\rFailureReasonq\u0000~\u0000Dsq\u0000~\u0000\n\u0001\u00be\u00b2"
+"\u00cdppsq\u0000~\u0000\f\u0001\u00be\u00b2\u00c2q\u0000~\u0000\u0011p\u0000sq\u0000~\u0000\u0000\u0001\u00be\u00b2\u00b7ppsq\u0000~\u0000\f\u0000\u001e\u00ecWpp\u0000sq\u0000~\u0000\n\u0000\u001e\u00ecLppsq\u0000"
+"~\u0000]\u0000\u001e\u00ecAq\u0000~\u0000\u0011psq\u0000~\u00001\u0000\u001e\u00ec>q\u0000~\u0000\u0011pq\u0000~\u0000bq\u0000~\u0000dq\u0000~\u0000@sq\u0000~\u0000:t\u0000Icom.sbc"
+".eia.bis.embus.service.netprovision.interfaces.ErrorDetailsM"
+"essageq\u0000~\u0000gsq\u0000~\u0000\n\u0001\u009f\u00c6[ppsq\u0000~\u00001\u0001\u009f\u00c6Pq\u0000~\u0000\u0011pq\u0000~\u00003sq\u0000~\u0000:q\u0000~\u0000=q\u0000~\u0000>"
+"q\u0000~\u0000@sq\u0000~\u0000:t\u0000\u000eFailureDetailsq\u0000~\u0000Dq\u0000~\u0000@sq\u0000~\u0000\n\u00018\u00df\u00dfppsq\u0000~\u00001\u00018\u00df\u00d4"
+"q\u0000~\u0000\u0011pq\u0000~\u0000Psq\u0000~\u0000:t\u0000\rSchemaVersionq\u0000~\u0000Dq\u0000~\u0000@sr\u0000\"com.sun.msv.g"
+"rammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/g"
+"rammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.E"
+"xpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006pa"
+"rentq\u0000~\u0000\u0080[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u0000\u0018\u0000"
+"\u0000\u00009pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpp"
+"ppppppppq\u0000~\u0000\tpppppppppppppppppppppppppppq\u0000~\u0000\u0012pppppppq\u0000~\u0000oppp"
+"pq\u0000~\u0000_q\u0000~\u0000rpppppppq\u0000~\u0000\u000bpq\u0000~\u0000\\q\u0000~\u0000qppppq\u0000~\u0000mq\u0000~\u0000hpppq\u0000~\u0000Opppp"
+"ppppq\u0000~\u0000\u0007ppppppq\u0000~\u0000\u0005pppppq\u0000~\u0000Mpq\u0000~\u00000q\u0000~\u0000Tpppppppppppq\u0000~\u0000\bppp"
+"q\u0000~\u0000Gpppppq\u0000~\u0000{pppppppppppppppq\u0000~\u0000Eppppppppppq\u0000~\u0000Zpppppppq\u0000~"
+"\u0000\u0006pppq\u0000~\u0000vpppppppppppppq\u0000~\u0000Hppppppppppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------");
        }

        protected Unmarshaller(com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ExceptionResponseTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        if (("FailureDetails" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  9 :
                        if (("DesignId" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        state = 12;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "SchemaVersion");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        if (("ActivityId" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        state = 9;
                        continue outer;
                    case  13 :
                        if (("MsgId" == ___local)&&("" == ___uri)) {
                            _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("Message" == ___local)&&("" == ___uri)) {
                            _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("Severity" == ___local)&&("" == ___uri)) {
                            _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("ExceptionType" == ___local)&&("" == ___uri)) {
                            _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  3 :
                        if (("OrderId" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  12 :
                        if (("FailureReason" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 13;
                            return ;
                        }
                        break;
                    case  18 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  16 :
                        if (("ErrorDetail" == ___local)&&("" == ___uri)) {
                            _FailureDetails = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorDetailsMessageImpl) spawnChildFromEnterElement((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorDetailsMessageImpl.class), 17, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _SchemaVersion = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  8 :
                        if (("ActivityId" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("DesignId" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "SchemaVersion");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  13 :
                        _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromLeaveElement((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  5 :
                        if (("OrderId" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  18 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  14 :
                        if (("FailureReason" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  17 :
                        if (("FailureDetails" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        state = 18;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  0 :
                        if (("SchemaVersion" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  13 :
                        _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromEnterAttribute((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  18 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  15 :
                        state = 18;
                        continue outer;
                    case  9 :
                        state = 12;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "SchemaVersion");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  6 :
                        state = 9;
                        continue outer;
                    case  13 :
                        _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromLeaveAttribute((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, ___uri, ___local, ___qname));
                        return ;
                    case  3 :
                        state = 6;
                        continue outer;
                    case  2 :
                        if (("SchemaVersion" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  18 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  15 :
                            state = 18;
                            continue outer;
                        case  9 :
                            state = 12;
                            continue outer;
                        case  0 :
                            attIdx = context.getAttribute("", "SchemaVersion");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  1 :
                            eatText1(value);
                            state = 2;
                            return ;
                        case  6 :
                            state = 9;
                            continue outer;
                        case  13 :
                            _FailureReason = ((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl) spawnChildFromText((com.sbc.eia.bis.embus.service.netprovision.interfaces.impl.ErrorMessageImpl.class), 14, value));
                            return ;
                        case  3 :
                            state = 6;
                            continue outer;
                        case  18 :
                            revertToParentFromText(value);
                            return ;
                        case  7 :
                            eatText2(value);
                            state = 8;
                            return ;
                        case  4 :
                            eatText3(value);
                            state = 5;
                            return ;
                        case  10 :
                            eatText4(value);
                            state = 11;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ActivityId = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _OrderId = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DesignId = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
